/**
 * AJAX AMSTERDAM — DONNÉES DES SAISONS (Multi)
 */
window.SEASONS_ajax = [

  /* ─── SAISON 2025/26 ─────────────────────────────────── */
  {
    id:         "ajax-2025-26",
    year:       "2025/26",
    league:     "Eredivisie",
    position:   2,
    totalTeams: 18,
    points:     84,
    played:     34,
    wins:       27,
    draws:      3,
    losses:     4,
    gf:         108,
    ga:         39,
    promoted:   [],
    relegated:  ["NAC Breda", "sc Heerenveen", "Heracles Almelo"],

    scorers: [
      { name: "Kasper Dolberg", detail: "BU · Danois", value: 40 },
    ],
    assists:  [],
    ratings:  [],

    transfers: [
      { type: "loan", name: "Robin Hack",            from: "Gladbach",    date: "Été 2025"                  },
      { type: "loan", name: "Arnau Puigmal",          from: "Almeria",     date: "Été 2025"                  },
      { type: "free", name: "Romke van de Pol",       from: "Vitesse",     date: "Été 2025"                  },
      { type: "sell", name: "Nicolas de la Cruz",     from: "Flamengo",    date: "Été 2025", amount: "7,5M €" },
      { type: "sell", name: "Joël Schingtienne",     from: "Venezia",     date: "Été 2025", amount: "1,6M €" },
      { type: "sell", name: "Andrea Compagno",        from: "Jeonbuk",     date: "Été 2025", amount: "2M €"   },
      { type: "free", name: "Taiyo Koga",             from: "Kashiwa",     date: "Été 2025"                  },
      { type: "free", name: "Takahiro Ohgihara",      from: "Kobe",        date: "Été 2025"                  },
    ],

    departures: [
      { type: "loan", name: "Marouane Bentaleb",      to: "JS Soualem",     date: "Été 2025"                   },
      { type: "loan", name: "Zakaria Ouzane",          to: "Helmond Sport",  date: "Été 2025"                   },
      { type: "loan", name: "Niilo Tarvajarvi",        to: "Gnistan",        date: "Été 2025"                   },
      { type: "loan", name: "Jinairo Johnson",         to: "Vitesse",        date: "Été 2025"                   },
      { type: "sell", name: "Wout Weghorst",           to: "Al-Kholood",     date: "Été 2025", amount: "1M €"   },
      { type: "sell", name: "Davy Klaassen",           to: "AEK Athènes",    date: "Été 2025", amount: "1,8M €" },
      { type: "sell", name: "Anton Gaaei",             to: "Atalanta",       date: "Été 2025", amount: "5,25M €"},
      { type: "loan", name: "Maher Carrizo",           to: "Wrexham",        date: "Été 2025"                   },
      { type: "sell", name: "Tijn Peters",             to: "Twente",         date: "Été 2025", amount: "135K €" },
      { type: "sell", name: "Elias Mechrouch",         to: "N.E.C.",         date: "Été 2025", amount: "250K €" },
    ],

    cup: {
      name: "KNVB Beker",
      rounds: [
        { result: "W", round: "2e tour",  score: "0 – 3", opponent: "Sparta Rotterdam (E)" },
        { result: "L", round: "3e tour",  score: "2 – 4", opponent: "PSV (D)"              },
      ],
    },

    cup2: {
      name: "UEFA Champions League",
      phase: "Phase de championnat : 22e · 3V 0N 5D · 9 pts → Barrage · Éliminé par Bergame",
      rounds: [
        { result: "W", round: "Barrage A", score: "2 – 1", opponent: "Bergame (D)"              },
        { result: "L", round: "Barrage R", score: "4 – 2", opponent: "Bergame (E) — 4-5 éliminé" },
      ],
    },

    playoffs: null,

    splash: {
      eyebrow:  "2025/26 · Ajax Amsterdam · Saison 1",
      lines:    ["DOLBERG.", "40 BUTS."],
      sub:      "Eredivisie · 2e · 84 pts · UCL Barrage",
      tagline:  "Vice-champions derrière Feyenoord. Kasper Dolberg écrit l'histoire du club avec 40 buts en une saison.",
    },

    matches: [
      { r:"W", tip:"Telstar (D) 9-0"           },
      { r:"L", tip:"Go Ahead Eagles (E) 2-1"   },
      { r:"W", tip:"Heracles Almelo (D) 1-0"   },
      { r:"W", tip:"FC Volendam (E) 0-4"       },
      { r:"W", tip:"PEC Zwolle (D) 3-0"        },
      { r:"L", tip:"PSV (E) 3-2"               },
      { r:"W", tip:"NAC Breda (D) 6-0"         },
      { r:"W", tip:"Sparta Rotterdam (E) 1-3"  },
      { r:"D", tip:"AZ (D) 1-1"                },
      { r:"W", tip:"FC Twente (E) 0-2"         },
      { r:"W", tip:"sc Heerenveen (D) 2-1"     },
      { r:"W", tip:"FC Utrecht (E) 0-1"        },
      { r:"W", tip:"Excelsior (D) 5-1"         },
      { r:"W", tip:"FC Groningen (D) 4-0"      },
      { r:"W", tip:"Fortuna Sittard (E) 0-3"   },
      { r:"W", tip:"Feyenoord (D) 4-1"         },
      { r:"W", tip:"N.E.C. (E) 2-3"            },
      { r:"W", tip:"Telstar (E) 0-5"           },
      { r:"W", tip:"Go Ahead Eagles (D) 3-0"   },
      { r:"W", tip:"FC Volendam (D) 2-1"       },
      { r:"W", tip:"Excelsior (E) 1-4"         },
      { r:"L", tip:"AZ (E) 2-0"                },
      { r:"W", tip:"Fortuna Sittard (D) 3-1"   },
      { r:"D", tip:"N.E.C. (D) 1-1"            },
      { r:"W", tip:"PEC Zwolle (E) 2-3"        },
      { r:"W", tip:"FC Groningen (E) 3-4"      },
      { r:"W", tip:"Sparta Rotterdam (D) 5-3"  },
      { r:"L", tip:"Feyenoord (E) 5-3"         },
      { r:"W", tip:"FC Twente (D) 2-0"         },
      { r:"D", tip:"Heracles Almelo (E) 2-2"   },
      { r:"W", tip:"NAC Breda (E) 2-4"         },
      { r:"W", tip:"PSV (D) 3-2"               },
      { r:"W", tip:"FC Utrecht (D) 4-1"        },
      { r:"W", tip:"sc Heerenveen (E) 1-6"     },
    ],

    standings: [
      { pos:1,  team:"Feyenoord",       j:34, g:29, n:3, l:2,  bp:95,  bc:28, db: 67, pts:90, zone:"promo" },
      { pos:2,  team:"Ajax",            j:34, g:27, n:3, l:4,  bp:108, bc:39, db: 69, pts:84, zone:"promo", highlight:true },
      { pos:3,  team:"PSV",             j:34, g:23, n:6, l:5,  bp:73,  bc:40, db: 33, pts:75, zone:"promo" },
      { pos:4,  team:"AZ",              j:34, g:18, n:10,l:6,  bp:75,  bc:47, db: 28, pts:64              },
      { pos:5,  team:"FC Groningen",    j:34, g:18, n:6, l:10, bp:71,  bc:53, db: 18, pts:60              },
      { pos:6,  team:"FC Utrecht",      j:34, g:14, n:5, l:15, bp:56,  bc:52, db:  4, pts:47              },
      { pos:7,  team:"N.E.C.",          j:34, g:12, n:9, l:13, bp:52,  bc:50, db:  2, pts:45              },
      { pos:8,  team:"PEC Zwolle",      j:34, g:12, n:9, l:13, bp:55,  bc:58, db: -3, pts:45              },
      { pos:9,  team:"Excelsior",       j:34, g:12, n:8, l:14, bp:46,  bc:58, db:-12, pts:44              },
      { pos:10, team:"Fortuna Sittard", j:34, g:11, n:9, l:14, bp:51,  bc:66, db:-15, pts:42              },
      { pos:11, team:"Go Ahead Eagles", j:34, g:11, n:6, l:17, bp:52,  bc:61, db: -9, pts:39              },
      { pos:12, team:"Sparta Rotterdam",j:34, g:9,  n:12,l:13, bp:51,  bc:61, db:-10, pts:39              },
      { pos:13, team:"FC Twente",       j:34, g:11, n:6, l:17, bp:48,  bc:63, db:-15, pts:39              },
      { pos:14, team:"Telstar",         j:34, g:9,  n:9, l:16, bp:51,  bc:69, db:-18, pts:36              },
      { pos:15, team:"FC Volendam",     j:34, g:10, n:4, l:20, bp:48,  bc:71, db:-23, pts:34              },
      { pos:16, team:"NAC Breda",       j:34, g:9,  n:3, l:22, bp:43,  bc:80, db:-37, pts:30, zone:"releg" },
      { pos:17, team:"sc Heerenveen",   j:34, g:6,  n:7, l:21, bp:27,  bc:63, db:-36, pts:25, zone:"releg" },
      { pos:18, team:"Heracles Almelo", j:34, g:5,  n:5, l:24, bp:42,  bc:85, db:-43, pts:20, zone:"releg" },
    ],
  },

  /* ─── SAISON 2026/27 ─────────────────────────────────── */
  {
    id:         "ajax-2026-27",
    year:       "2026/27",
    league:     "Eredivisie",
    position:   3,
    totalTeams: 18,
    points:     71,
    played:     34,
    wins:       22,
    draws:      5,
    losses:     7,
    gf:         73,
    ga:         32,
    promoted:   [],
    relegated:  ["FC Eindhoven", "Fortuna Sittard", "Roda JC"],

    scorers: [],
    assists: [],
    ratings: [],

    transfers: [
      { type: "buy",  name: "Vítězslav Jaroš",              from: "Liverpool",            date: "Juin 2026", amount: "12,25M €" },
      { type: "free", name: "Dan-Axel Zagadou",             from: "VfB Stuttgart",        date: "Juil. 2026"                  },
      { type: "free", name: "Julian Brandt",                from: "Borussia Dortmund",    date: "Juil. 2026"                  },
      { type: "free", name: "Jorge Franco",                 from: "Zaragoza B",           date: "Juil. 2026"                  },
      { type: "buy",  name: "Wojciech Szczęsny",            from: "Barcelone",            date: "Juil. 2026", amount: "7,5M €"  },
      { type: "buy",  name: "Arnau Puigmal",                from: "Almería",              date: "Juil. 2026", amount: "14,5M €" },
      { type: "buy",  name: "Pablo Solari",                 from: "Spartak Moscou",       date: "Sep. 2026", amount: "6,25M €" },
      { type: "buy",  name: "Nadiem Amiri",                 from: "FSV Mainz 05",         date: "Jan. 2027", amount: "15,75M €" },
      { type: "free", name: "Sailson Furtado Fernandes",    from: "FC Dordrecht",         date: "Jan. 2027"                  },
      { type: "loan", name: "Luis Sinisterra",              from: "Bournemouth",          date: "Jan. 2027"                  },
      { type: "loan", name: "Nicolò Cambiaghi",             from: "Bologna",              date: "Fév. 2027"                  },
    ],

    departures: [
      { type: "sell", name: "Steven Berghuis",       to: "León",                   date: "Juin 2026",  amount: "275K €"  },
      { type: "sell", name: "Kian Fitz-Jim",         to: "Norwich",                date: "Juin 2026",  amount: "5,25M €" },
      { type: "sell", name: "Chuba Akpom",           to: "Ipswich",                date: "Juin 2026",  amount: "8M €"    },
      { type: "free", name: "Oleksandr Zinchenko",   to: "Vigo",                   date: "Juil. 2026"                  },
      { type: "sell", name: "Joël Schingtienne",    to: "Standard",               date: "Juil. 2026", amount: "2,1M €"  },
      { type: "free", name: "Lucas Jetten",          to: "Benfica",                date: "Juil. 2026"                  },
      { type: "free", name: "Ethan Butera",          to: "Bournemouth",            date: "Juil. 2026"                  },
      { type: "sell", name: "Maarten Paes",          to: "Al-Riyadh",              date: "Juil. 2026", amount: "2M €"    },
      { type: "loan", name: "Jinairo Johnson",       to: "FC Eindhoven",           date: "Juil. 2026"                  },
      { type: "sell", name: "Ahmetcan Kaplan",       to: "Al-Taawun",              date: "Juil. 2026", amount: "1,5M €"  },
      { type: "loan", name: "Jorge Franco",          to: "Sant Andreu",            date: "Juil. 2026"                  },
      { type: "loan", name: "Pharell Nash",          to: "Wolves",                 date: "Juil. 2026"                  },
      { type: "loan", name: "Aaron Bouwman",         to: "Arminia Bielefeld",      date: "Juil. 2026"                  },
      { type: "loan", name: "Daniel Johan Skaarud",  to: "NAC Breda",              date: "Juil. 2026"                  },
      { type: "loan", name: "Hasan Ayyildiz",        to: "Bursaspor",              date: "Juil. 2026"                  },
      { type: "sell", name: "Owen Wijndal",          to: "Wolves",                 date: "Aoû. 2026",  amount: "5,25M €" },
      { type: "sell", name: "Sivert Mannsverk",      to: "Bergame",                date: "Aoû. 2026",  amount: "16M €"   },
      { type: "loan", name: "Marvyn Muzungu",        to: "Nancy",                  date: "Aoû. 2026"                  },
      { type: "loan", name: "Mark Engel",            to: "Vitesse",                date: "Sep. 2026"                  },
      { type: "sell", name: "Levi Acheampong",       to: "PSV",                    date: "Sep. 2026",  amount: "575K €"  },
      { type: "loan", name: "Emre Ünüvar",           to: "Heracles Almelo",        date: "Sep. 2026"                  },
      { type: "loan", name: "David Kalokoh",         to: "Estoril Praia",          date: "Sep. 2026"                  },
      { type: "loan", name: "Sean Steur",            to: "Fortuna Düsseldorf",     date: "Jan. 2027"                  },
      { type: "loan", name: "Martin Henrion",        to: "SK Lierse",              date: "Jan. 2027"                  },
      { type: "loan", name: "Luka Vieillevoye",      to: "Penafiel",               date: "Jan. 2027"                  },
      { type: "loan", name: "Nafairon Landvreugd",   to: "Vitesse",                date: "Jan. 2027"                  },
      { type: "loan", name: "Oliver Edvardsen",      to: "Norwich",                date: "Jan. 2027"                  },
      { type: "loan", name: "Andrea Compagno",       to: "Girona",                 date: "Jan. 2027"                  },
      { type: "loan", name: "Lucas Rosa",            to: "Espanyol",               date: "Jan. 2027"                  },
      { type: "loan", name: "Skye Vink",             to: "Heracles Almelo",        date: "Fév. 2027"                  },
      { type: "loan", name: "Mark Verkuijl",         to: "Heracles Almelo",        date: "Fév. 2027"                  },
      { type: "sell", name: "Takahiro Ohgihara",     to: "G-Osaka",                date: "Fév. 2027",  amount: "60K €"   },
      { type: "loan", name: "Josip Šutalo",          to: "Dinamo Zagreb",          date: "Fév. 2027"                  },
    ],

    cup: {
      name: "KNVB Beker",
      rounds: [
        { result: "W", round: "2e tour", score: "0 – 5", opponent: "IJsselmeervogels (E)" },
        { result: "W", round: "3e tour", score: "2 – 1", opponent: "FC Groningen (D)"     },
        { result: "W", round: "Quart",   score: "2 – 4", opponent: "NAC Breda (E)"        },
        { result: "W", round: "Demi",    score: "2 – 3", opponent: "FC Volendam (E)"      },
        { result: "L", round: "Finale",  score: "2 – 1", opponent: "Feyenoord (N)"        },
      ],
    },

    cup2: {
      name:  "UEFA Champions League",
      phase: "Phase de championnat : 22e sur 36 · 2V 3N 3D · 9 pts → Barrage · Éliminé par Lille (2-3 cumulé)",
      rounds: [
        { result: "D", round: "Barrage · Aller",  score: "1 – 1", opponent: "LOSC Lille (D)"            },
        { result: "L", round: "Barrage · Retour", score: "2 – 1", opponent: "LOSC Lille (E) — 2-3 élim." },
      ],
    },

    playoffs: null,

    splash: {
      eyebrow:  "2026/27 · Ajax Amsterdam · Saison 2",
      lines:    ["SUR LE PODIUM.", "CAP SUR LA C1."],
      sub:      "Eredivisie · 3e · 71 pts · Qualifié en Ligue des Champions",
      tagline:  "Derrière Feyenoord et le PSV, l'Ajax décroche son billet direct pour la Ligue des Champions — malgré une finale de coupe cruelle perdue contre l'éternel rival.",
    },

    matches: [
      { r:"W", tip:"PSV (E) 0-2"                },
      { r:"W", tip:"Roda JC (D) 4-3"            },
      { r:"W", tip:"PEC Zwolle (E) 1-2"         },
      { r:"W", tip:"AZ (D) 2-1"                 },
      { r:"W", tip:"ADO Den Haag (E) 0-2"       },
      { r:"L", tip:"Feyenoord (D) 2-3"          },
      { r:"D", tip:"FC Utrecht (D) 0-0"         },
      { r:"W", tip:"Telstar (E) 0-2"            },
      { r:"D", tip:"Fortuna Sittard (D) 2-2"    },
      { r:"W", tip:"Sparta Rotterdam (D) 4-1"   },
      { r:"W", tip:"FC Eindhoven (E) 1-4"       },
      { r:"W", tip:"Excelsior (D) 4-0"          },
      { r:"W", tip:"N.E.C. (E) 0-1"             },
      { r:"W", tip:"FC Groningen (D) 3-1"       },
      { r:"L", tip:"Go Ahead Eagles (E) 1-0"    },
      { r:"W", tip:"FC Volendam (E) 0-3"        },
      { r:"W", tip:"FC Twente (D) 6-3"          },
      { r:"W", tip:"Telstar (D) 4-1"            },
      { r:"D", tip:"Fortuna Sittard (E) 0-0"    },
      { r:"L", tip:"PSV (D) 1-2"                },
      { r:"L", tip:"FC Utrecht (E) 1-0"         },
      { r:"W", tip:"Excelsior (E) 1-2"          },
      { r:"D", tip:"N.E.C. (D) 0-0"             },
      { r:"D", tip:"FC Groningen (E) 1-1"       },
      { r:"W", tip:"ADO Den Haag (D) 4-0"       },
      { r:"L", tip:"Feyenoord (E) 1-0"          },
      { r:"W", tip:"FC Volendam (D) 4-0"        },
      { r:"L", tip:"AZ (E) 3-2"                 },
      { r:"L", tip:"Sparta Rotterdam (E) 2-1"   },
      { r:"W", tip:"FC Eindhoven (D) 4-0"       },
      { r:"W", tip:"Roda JC (E) 2-3"            },
      { r:"W", tip:"PEC Zwolle (D) 1-0"         },
      { r:"W", tip:"Go Ahead Eagles (D) 1-0"    },
      { r:"W", tip:"FC Twente (E) 1-2"          },
    ],

    standings: [
      { pos:1,  team:"Feyenoord",        j:34, g:28, n:5,  l:1,  bp:102, bc:21, db: 81, pts:89, zone:"promo" },
      { pos:2,  team:"PSV",              j:34, g:27, n:5,  l:2,  bp:84,  bc:29, db: 55, pts:86, zone:"promo" },
      { pos:3,  team:"Ajax",             j:34, g:22, n:5,  l:7,  bp:73,  bc:32, db: 41, pts:71, zone:"promo", highlight:true },
      { pos:4,  team:"FC Utrecht",       j:34, g:19, n:6,  l:9,  bp:59,  bc:44, db: 15, pts:63              },
      { pos:5,  team:"Go Ahead Eagles",  j:34, g:18, n:5,  l:11, bp:71,  bc:56, db: 15, pts:59              },
      { pos:6,  team:"N.E.C.",           j:34, g:17, n:7,  l:10, bp:50,  bc:39, db: 11, pts:58              },
      { pos:7,  team:"FC Twente",        j:34, g:15, n:9,  l:10, bp:52,  bc:57, db: -5, pts:54              },
      { pos:8,  team:"AZ",               j:34, g:16, n:5,  l:13, bp:67,  bc:42, db: 25, pts:53              },
      { pos:9,  team:"FC Groningen",     j:34, g:13, n:9,  l:12, bp:52,  bc:55, db: -3, pts:48              },
      { pos:10, team:"ADO Den Haag",     j:34, g:13, n:6,  l:15, bp:48,  bc:52, db: -4, pts:45              },
      { pos:11, team:"FC Volendam",      j:34, g:11, n:8,  l:15, bp:50,  bc:62, db:-12, pts:41              },
      { pos:12, team:"Excelsior",        j:34, g:8,  n:12, l:14, bp:40,  bc:52, db:-12, pts:36              },
      { pos:13, team:"Sparta Rotterdam", j:34, g:10, n:5,  l:19, bp:52,  bc:74, db:-22, pts:35              },
      { pos:14, team:"Telstar",          j:34, g:9,  n:2,  l:23, bp:40,  bc:85, db:-45, pts:29              },
      { pos:15, team:"PEC Zwolle",       j:34, g:5,  n:10, l:19, bp:35,  bc:61, db:-26, pts:25              },
      { pos:16, team:"FC Eindhoven",     j:34, g:5,  n:8,  l:21, bp:35,  bc:67, db:-32, pts:23, zone:"releg" },
      { pos:17, team:"Fortuna Sittard",  j:34, g:3,  n:11, l:20, bp:38,  bc:76, db:-38, pts:20, zone:"releg" },
      { pos:18, team:"Roda JC",          j:34, g:4,  n:8,  l:22, bp:31,  bc:75, db:-44, pts:20, zone:"releg" },
    ],
  },

  /* ─── SAISON 2027/28 ─────────────────────────────────── */
  {
    id:         "ajax-2027-28",
    year:       "2027/28",
    league:     "Eredivisie",
    position:   2,
    totalTeams: 18,
    points:     82,
    played:     34,
    wins:       27,
    draws:      1,
    losses:     6,
    gf:         105,
    ga:         25,
    promoted:   [],
    relegated:  ["ADO Den Haag", "Telstar", "FC Volendam"],

    scorers: [],
    assists: [],
    ratings: [],

    transfers: [
      { type: "buy",  name: "Nicolò Cambiaghi",   from: "Bologna",          date: "Juin 2027", amount: "7,25M €"  },
      { type: "loan", name: "Carl Rushworth",      from: "Brighton",         date: "Juil. 2027"                   },
      { type: "buy",  name: "Mohamed-Ali Cho",     from: "OGC Nice",         date: "Juil. 2027", amount: "7,5M €"  },
      { type: "buy",  name: "Pablo Campos",        from: "Cremonese",        date: "Juil. 2027", amount: "1,8M €"  },
      { type: "buy",  name: "Jaka Bijol",          from: "Leeds",            date: "Juil. 2027", amount: "24M €"   },
      { type: "buy",  name: "Nayef Aguerd",        from: "Marseille",        date: "Juil. 2027", amount: "10M €"   },
      { type: "buy",  name: "Dominic Vincze",      from: "SK Rapid",         date: "Aoû. 2027",  amount: "8,75M €" },
      { type: "buy",  name: "Louis Leroux",        from: "FC Nantes",        date: "Aoû. 2027",  amount: "7,75M €" },
      { type: "free", name: "Fred",                from: "Libre",            date: "Sep. 2027"                   },
      { type: "buy",  name: "Ben Gannon Doak",     from: "Bournemouth",      date: "Jan. 2028",  amount: "104M €"  },
      { type: "buy",  name: "Tiago Gabriel",       from: "Lecce",            date: "Jan. 2028",  amount: "19,75M €" },
      { type: "buy",  name: "Ousmane Diao",        from: "FC Midtjylland",   date: "Jan. 2028",  amount: "6,75M €" },
      { type: "buy",  name: "Jusuf Gazibegović",   from: "Celesti",          date: "Jan. 2028",  amount: "4,3M €"  },
      { type: "buy",  name: "Adam Brett",          from: "Brighton",         date: "Jan. 2028",  amount: "65K €"   },
      { type: "buy",  name: "Fábio Vieira",        from: "AS Roma",          date: "Jan. 2028",  amount: "7,5M €"  },
      { type: "buy",  name: "Luke Shaw",           from: "Man Utd",          date: "Jan. 2028",  amount: "12,75M €" },
    ],

    departures: [
      { type: "loan", name: "Jan Faberski",         to: "Brøndby IF",        date: "Juin 2027"                   },
      { type: "sell", name: "Takahiro Tomiyasu",    to: "Marseille",         date: "Juin 2027", amount: "20,5M €" },
      { type: "sell", name: "Oliver Edvardsen",     to: "Norwich",           date: "Juin 2027", amount: "4,7M €"  },
      { type: "free", name: "Zakaria Ouazane",      to: "N.E.C.",            date: "Juil. 2027"                  },
      { type: "free", name: "Luca Messori",         to: "PSV",               date: "Juil. 2027"                  },
      { type: "free", name: "Anass Moumane",        to: "Stockport",         date: "Juil. 2027"                  },
      { type: "sell", name: "Julian Rijkhoff",      to: "Karlsruher SC",     date: "Juil. 2027", amount: "3M €"   },
      { type: "loan", name: "Thijmen Romers",       to: "FC Emmen",          date: "Juil. 2027"                  },
      { type: "loan", name: "Marouane Bentaleb",    to: "TOP Oss",           date: "Juil. 2027"                  },
      { type: "sell", name: "Maher Carrizo",        to: "Real Sociedad",     date: "Juil. 2027", amount: "12,25M €" },
      { type: "sell", name: "Julian Brandt",        to: "Casciavit",         date: "Juil. 2027", amount: "25M €"  },
      { type: "loan", name: "Vítězslav Jaroš",      to: "Sporting CP",       date: "Juil. 2027"                  },
      { type: "loan", name: "Noah Tamsamani",       to: "Fortuna Sittard",   date: "Juil. 2027"                  },
      { type: "loan", name: "Marvyn Muzungu",       to: "Famalicão",         date: "Juil. 2027"                  },
      { type: "loan", name: "Luka Vieillevoye",     to: "Hellas Verona",     date: "Juil. 2027"                  },
      { type: "sell", name: "Youri Baas",           to: "Borussia Dortmund", date: "Juil. 2027", amount: "38M €"  },
      { type: "sell", name: "Ko Itakura",           to: "Torino",            date: "Juil. 2027", amount: "9M €"   },
      { type: "loan", name: "Tristan Gooijer",      to: "Valencia",          date: "Aoû. 2027"                  },
      { type: "loan", name: "Soufiane Guessous",    to: "De Graafschap",     date: "Aoû. 2027"                  },
      { type: "loan", name: "Aaron Bouwman",        to: "Hellas Verona",     date: "Aoû. 2027"                  },
      { type: "loan", name: "David Kalokoh",        to: "Moreirense",        date: "Aoû. 2027"                  },
      { type: "loan", name: "Romke van de Pol",     to: "De Graafschap",     date: "Aoû. 2027"                  },
      { type: "loan", name: "Kennynho Kasanwirjo",  to: "FC Emmen",          date: "Aoû. 2027"                  },
      { type: "loan", name: "Don-Angelo Konadu",    to: "MSV Duisburg",      date: "Aoû. 2027"                  },
      { type: "loan", name: "Eloi Gómez",           to: "FC Groningen",      date: "Aoû. 2027"                  },
      { type: "loan", name: "Gerald Alders",        to: "Frosinone",         date: "Aoû. 2027"                  },
      { type: "loan", name: "Skye Vink",            to: "Almere City",       date: "Aoû. 2027"                  },
      { type: "loan", name: "Emre Ünüvar",          to: "Juve Stabia",       date: "Aoû. 2027"                  },
      { type: "sell", name: "Arnau Puigmal",        to: "Fiorentina",        date: "Aoû. 2027", amount: "11,75M €" },
      { type: "loan", name: "Sean Steur",           to: "Frosinone",         date: "Aoû. 2027"                  },
      { type: "loan", name: "Mark Verkuijl",        to: "MSV Duisburg",      date: "Aoû. 2027"                  },
      { type: "loan", name: "Jorge Franco",         to: "Fortuna Sittard",   date: "Sep. 2027"                  },
      { type: "loan", name: "Xander Newstead",      to: "MSV Duisburg",      date: "Jan. 2028"                  },
      { type: "sell", name: "Jinairo Johnson",      to: "AZ",                date: "Jan. 2028", amount: "1,1M €"  },
      { type: "loan", name: "Nick Verschuren",      to: "Helmond Sport",     date: "Jan. 2028"                  },
      { type: "loan", name: "Martin Henrion",       to: "Vitesse",           date: "Jan. 2028"                  },
      { type: "sell", name: "Luka Vieillevoye",     to: "Udinese",           date: "Jan. 2028", amount: "4,9M €"  },
      { type: "loan", name: "Andrea Compagno",      to: "Norwich",           date: "Jan. 2028"                  },
      { type: "loan", name: "Jan Faberski",         to: "Torino",            date: "Jan. 2028"                  },
      { type: "loan", name: "Mika Godts",           to: "Bournemouth",       date: "Jan. 2028"                  },
      { type: "loan", name: "Paulo Da Silva",       to: "FC Emmen",          date: "Jan. 2028"                  },
      { type: "loan", name: "Thom Veenbergen",      to: "SC Cambuur",        date: "Jan. 2028"                  },
      { type: "loan", name: "Kasper Dolberg",       to: "Nott'm Forest",     date: "Fév. 2028"                  },
      { type: "loan", name: "Abdellah Ouazane",     to: "Rio Ave",           date: "Fév. 2028"                  },
      { type: "loan", name: "Chris Howkins",        to: "Fuego FC",          date: "Fév. 2028"                  },
    ],

    cup: {
      name: "KNVB Beker",
      rounds: [
        { result: "W", round: "2e tour", score: "7 – 0", opponent: "De Treffers (D)" },
        { result: "W", round: "3e tour", score: "1 – 2", opponent: "NAC Breda (E)"   },
        { result: "L", round: "Quart",   score: "0 – 1", opponent: "PSV (D)"         },
      ],
    },

    cup2: {
      name:  "UEFA Champions League",
      phase: "Qualifs franchies · Phase de championnat : 19e sur 36 · 3V 3N 2D · 12 pts → Barrage · Éliminé par l'Atlético Madrid",
      rounds: [
        { result: "W", round: "3e Préliminaire", score: "5 – 1", opponent: "KRC Genk"        },
        { result: "W", round: "Barrage d'accès", score: "6 – 2", opponent: "RC Lens"         },
        { result: "L", round: "8e · Barrage",    score: "4 – 5", opponent: "Atlético Madrid" },
      ],
    },

    playoffs: null,

    splash: {
      eyebrow:  "2027/28 · Ajax Amsterdam · Saison 3",
      lines:    ["105 BUTS.", "VICE-CHAMPIONS."],
      sub:      "Eredivisie · 2e · 82 pts · Qualifié en Ligue des Champions",
      tagline:  "Une attaque de feu — 105 buts, +80 de différence, un seul nul de toute la saison. L'Ajax pousse Feyenoord jusqu'au bout et retrouvera la Ligue des Champions.",
    },

    matches: [
      { r:"W", tip:"FC Volendam (D) 4-0"        },
      { r:"W", tip:"Go Ahead Eagles (D) 3-0"    },
      { r:"W", tip:"FC Groningen (E) 0-5"       },
      { r:"W", tip:"PEC Zwolle (E) 1-3"         },
      { r:"W", tip:"Willem II (D) 4-1"          },
      { r:"W", tip:"NAC Breda (E) 2-5"          },
      { r:"W", tip:"Sparta Rotterdam (D) 6-0"   },
      { r:"W", tip:"Excelsior (E) 1-2"          },
      { r:"W", tip:"FC Utrecht (E) 1-2"         },
      { r:"W", tip:"PSV (D) 2-0"                },
      { r:"L", tip:"Feyenoord (E) 1-0"          },
      { r:"W", tip:"Telstar (D) 4-0"            },
      { r:"W", tip:"FC Twente (E) 1-4"          },
      { r:"W", tip:"N.E.C. (D) 3-0"             },
      { r:"W", tip:"AZ (E) 0-1"                 },
      { r:"W", tip:"ADO Den Haag (D) 7-0"       },
      { r:"L", tip:"sc Heerenveen (E) 2-0"      },
      { r:"L", tip:"FC Utrecht (D) 2-3"         },
      { r:"L", tip:"PSV (E) 2-1"                },
      { r:"W", tip:"FC Volendam (E) 0-4"        },
      { r:"W", tip:"PEC Zwolle (D) 3-0"         },
      { r:"W", tip:"FC Twente (D) 3-0"          },
      { r:"L", tip:"N.E.C. (E) 3-1"             },
      { r:"W", tip:"AZ (D) 3-0"                 },
      { r:"W", tip:"Sparta Rotterdam (E) 0-2"   },
      { r:"W", tip:"Excelsior (D) 3-1"          },
      { r:"W", tip:"NAC Breda (D) 4-0"          },
      { r:"W", tip:"Go Ahead Eagles (E) 1-2"    },
      { r:"L", tip:"Feyenoord (D) 2-4"          },
      { r:"W", tip:"Telstar (E) 0-5"            },
      { r:"W", tip:"Willem II (E) 0-2"          },
      { r:"W", tip:"FC Groningen (D) 8-1"       },
      { r:"D", tip:"ADO Den Haag (E) 0-0"       },
      { r:"W", tip:"sc Heerenveen (D) 5-0"      },
    ],

    standings: [
      { pos:1,  team:"Feyenoord",        j:34, g:27, n:4,  l:3,  bp:110, bc:34, db: 76, pts:85, zone:"promo" },
      { pos:2,  team:"Ajax",             j:34, g:27, n:1,  l:6,  bp:105, bc:25, db: 80, pts:82, zone:"promo", highlight:true },
      { pos:3,  team:"PSV",              j:34, g:25, n:4,  l:5,  bp:72,  bc:34, db: 38, pts:79, zone:"promo" },
      { pos:4,  team:"FC Twente",        j:34, g:20, n:4,  l:10, bp:57,  bc:51, db:  6, pts:64              },
      { pos:5,  team:"Excelsior",        j:34, g:17, n:9,  l:8,  bp:63,  bc:36, db: 27, pts:60              },
      { pos:6,  team:"Go Ahead Eagles",  j:34, g:18, n:5,  l:11, bp:54,  bc:52, db:  2, pts:59              },
      { pos:7,  team:"FC Utrecht",       j:34, g:16, n:7,  l:11, bp:57,  bc:47, db: 10, pts:55              },
      { pos:8,  team:"N.E.C.",           j:34, g:15, n:6,  l:13, bp:56,  bc:49, db:  7, pts:51              },
      { pos:9,  team:"Sparta Rotterdam", j:34, g:13, n:4,  l:17, bp:41,  bc:67, db:-26, pts:43              },
      { pos:10, team:"FC Groningen",     j:34, g:12, n:6,  l:16, bp:41,  bc:60, db:-19, pts:42              },
      { pos:11, team:"sc Heerenveen",    j:34, g:10, n:10, l:14, bp:39,  bc:53, db:-14, pts:40              },
      { pos:12, team:"AZ",               j:34, g:10, n:5,  l:19, bp:35,  bc:44, db: -9, pts:35              },
      { pos:13, team:"NAC Breda",        j:34, g:9,  n:7,  l:18, bp:41,  bc:62, db:-21, pts:34              },
      { pos:14, team:"Willem II",        j:34, g:9,  n:6,  l:19, bp:40,  bc:60, db:-20, pts:33              },
      { pos:15, team:"PEC Zwolle",       j:34, g:8,  n:6,  l:20, bp:40,  bc:71, db:-31, pts:30              },
      { pos:16, team:"ADO Den Haag",     j:34, g:8,  n:5,  l:21, bp:45,  bc:71, db:-26, pts:29, zone:"releg" },
      { pos:17, team:"Telstar",          j:34, g:7,  n:5,  l:22, bp:46,  bc:88, db:-42, pts:26, zone:"releg" },
      { pos:18, team:"FC Volendam",      j:34, g:4,  n:8,  l:22, bp:31,  bc:69, db:-38, pts:20, zone:"releg" },
    ],
  },

  /* ─── SAISON 2028/29 · AJAX → CHELSEA (deux clubs) ───── */
  {
    id:         "ajax-2028-29",
    year:       "2028/29",
    league:     "Eredivisie → Premier League",
    position:   6,
    totalTeams: 20,
    points:     67,
    played:     38,
    wins:       29,
    draws:      4,
    losses:     5,
    gf:         99,
    ga:         35,

    split: true,

    splash: {
      eyebrow:  "2028/29 · Saison 4 · Ajax → Chelsea",
      lines:    ["UN HIVER,", "DEUX CLUBS."],
      sub:      "Eredivisie 1ᵉʳ → Premier League 6ᵉ · Qualifié en Europa League",
      tagline:  "Leader de l'Eredivisie, Arq Queft quitte l'Ajax en plein hiver pour reprendre un Chelsea 15ᵉ et à la dérive — et le hisse jusqu'à l'Europe.",
    },

    // Combinés (pour la grille des saisons) : 38 matchs de championnat dirigés, 29V 4N 5D
    matches: [
      { r:"W", tip:"Sparta Rotterdam (E) 0-5" },
      { r:"W", tip:"Fortuna Sittard (D) 5-0" },
      { r:"W", tip:"Excelsior (E) 0-1" },
      { r:"W", tip:"FC Twente (D) 6-0" },
      { r:"W", tip:"sc Heerenveen (D) 5-1" },
      { r:"W", tip:"PEC Zwolle (E) 0-4" },
      { r:"W", tip:"FC Eindhoven (D) 5-1" },
      { r:"W", tip:"N.E.C. (E) 0-2" },
      { r:"D", tip:"Go Ahead Eagles (D) 1-1" },
      { r:"L", tip:"PSV (D) 0-2" },
      { r:"L", tip:"Feyenoord (E) 2-1" },
      { r:"W", tip:"AZ (D) 2-0" },
      { r:"W", tip:"NAC Breda (E) 0-4" },
      { r:"W", tip:"FC Utrecht (E) 2-3" },
      { r:"W", tip:"De Graafschap (D) 4-1" },
      { r:"W", tip:"Willem II (E) 1-2" },
      { r:"W", tip:"FC Groningen (D) 4-0" },
      { r:"W", tip:"Southampton (E) 1-3" },
      { r:"W", tip:"Everton (D) 5-2" },
      { r:"W", tip:"Bournemouth (E) 1-3" },
      { r:"W", tip:"Newcastle (E) 1-3" },
      { r:"W", tip:"Fulham (D) 2-0" },
      { r:"W", tip:"Crystal Palace (D) 3-0" },
      { r:"W", tip:"Nott'm Forest (D) 1-0" },
      { r:"L", tip:"Ipswich (E) 3-0" },
      { r:"D", tip:"Spurs (D) 1-1" },
      { r:"W", tip:"Leeds (E) 1-3" },
      { r:"W", tip:"Man Utd (E) 1-2" },
      { r:"L", tip:"Brentford (D) 0-1" },
      { r:"D", tip:"Aston Villa (D) 2-2" },
      { r:"D", tip:"Wolves (E) 0-0" },
      { r:"W", tip:"Everton (E) 1-4" },
      { r:"W", tip:"Southampton (D) 3-1" },
      { r:"W", tip:"Bournemouth (D) 4-1" },
      { r:"W", tip:"Man City (D) 1-0" },
      { r:"W", tip:"West Ham (E) 3-4" },
      { r:"W", tip:"Liverpool (D) 1-0" },
      { r:"L", tip:"Arsenal (E) 4-0" },
    ],

    stints: [
      /* ─ Étape 1 : AFC Ajax ─ */
      {
        club:        "AFC Ajax",
        logo:        "logo-ajax.png",
        accent:      "#cc0000",
        phase:       "PREMIÈRE PARTIE",
        tenure:      "Juillet → Décembre 2028",
        league:      "Eredivisie",
        positionText:"1ᵉʳ au moment du départ",
        record:      { played:17, wins:14, draws:1, losses:2, gf:54, ga:11 },
        note:        "Arq Queft laisse l'Ajax en tête de l'Eredivisie pour rejoindre Chelsea.",

        matches: [
          { r:"W", tip:"Sparta Rotterdam (E) 0-5" },
          { r:"W", tip:"Fortuna Sittard (D) 5-0" },
          { r:"W", tip:"Excelsior (E) 0-1" },
          { r:"W", tip:"FC Twente (D) 6-0" },
          { r:"W", tip:"sc Heerenveen (D) 5-1" },
          { r:"W", tip:"PEC Zwolle (E) 0-4" },
          { r:"W", tip:"FC Eindhoven (D) 5-1" },
          { r:"W", tip:"N.E.C. (E) 0-2" },
          { r:"D", tip:"Go Ahead Eagles (D) 1-1" },
          { r:"L", tip:"PSV (D) 0-2" },
          { r:"L", tip:"Feyenoord (E) 2-1" },
          { r:"W", tip:"AZ (D) 2-0" },
          { r:"W", tip:"NAC Breda (E) 0-4" },
          { r:"W", tip:"FC Utrecht (E) 2-3" },
          { r:"W", tip:"De Graafschap (D) 4-1" },
          { r:"W", tip:"Willem II (E) 1-2" },
          { r:"W", tip:"FC Groningen (D) 4-0" },
        ],

        cups: [
          {
            name:  "UEFA Champions League",
            phase: "Qualifs franchies (OL, FC Porto) · 8ᵉ de la phase de championnat au départ",
            rounds: [
              { result:"W", round:"3e tour Q.",  score:"0-0 · 0-1", opponent:"Olympique Lyonnais" },
              { result:"W", round:"Barrage",     score:"2-2 · 3-0", opponent:"FC Porto"           },
              { result:"W", round:"J1",          score:"4-0",       opponent:"FC Midtjylland (D)" },
              { result:"L", round:"J2",          score:"0-2",       opponent:"Villarreal (D)"     },
              { result:"W", round:"J3",          score:"5-4",       opponent:"R. Madrid (D)"      },
              { result:"L", round:"J4",          score:"4-3",       opponent:"Arsenal (E)"        },
              { result:"W", round:"J5",          score:"5-1",       opponent:"Casciavit (D)"      },
              { result:"W", round:"J6",          score:"1-4",       opponent:"Dinamo (E)"         },
            ],
          },
          {
            name: "Coupe des Pays-Bas",
            rounds: [
              { result:"W", round:"2e tour", score:"0-2", opponent:"Heracles Almelo (E)" },
            ],
          },
          {
            name: "Super Coupe des Pays-Bas",
            rounds: [
              { result:"L", round:"Finale", score:"5-2", opponent:"Feyenoord (E)" },
            ],
          },
        ],

        transfers: [
          { type:"free", name:"Davide Frattesi",    from:"Blu-neri",        date:"Juil. 2028" },
          { type:"buy",  name:"Trai Hume",          from:"Sunderland",      date:"Juil. 2028", amount:"26,5M €"  },
          { type:"buy",  name:"Álvaro Fernández",   from:"Coruña",          date:"Juil. 2028", amount:"6M €"     },
          { type:"buy",  name:"Mikayil Faye",       from:"Rennes",          date:"Aoû. 2028",  amount:"15,5M €"  },
          { type:"buy",  name:"Josh Acheampong",    from:"Chelsea",         date:"Aoû. 2028",  amount:"39,5M €"  },
          { type:"buy",  name:"Marcos Peña",        from:"Famalicão",       date:"Aoû. 2028",  amount:"11,75M €" },
          { type:"buy",  name:"Izan Merino",        from:"Málaga",          date:"Sep. 2028",  amount:"12,5M €"  },
          { type:"loan", name:"Antonio Vergara",    from:"Como",            date:"Sep. 2028" },
        ],
        departures: [
          { type:"sell", name:"Taiyo Koga",          to:"PSV",                 date:"Juin 2028",  amount:"17,75M €" },
          { type:"sell", name:"Youri Regeer",        to:"Norwich",             date:"Juin 2028",  amount:"8,75M €"  },
          { type:"sell", name:"Tristan Gooijer",     to:"Valencia",            date:"Juin 2028",  amount:"2,6M €"   },
          { type:"sell", name:"Kasper Dolberg",      to:"Nott'm Forest",       date:"Juin 2028",  amount:"31,5M €"  },
          { type:"sell", name:"Mika Godts",          to:"Bournemouth",         date:"Juin 2028",  amount:"24M €"    },
          { type:"free", name:"Gastón Ávila",        to:"Famalicão",           date:"Juil. 2028" },
          { type:"free", name:"Gerald Alders",       to:"Reims",               date:"Juil. 2028" },
          { type:"free", name:"Leroy Fränkel",       to:"Willem II",           date:"Juil. 2028" },
          { type:"free", name:"Luca Nas",            to:"Juventus",            date:"Juil. 2028" },
          { type:"sell", name:"Lucas Rosa",          to:"Girona",              date:"Juil. 2028", amount:"4,6M €"   },
          { type:"sell", name:"Dies Janse",          to:"Eintracht Frankfurt", date:"Juil. 2028", amount:"5,5M €"   },
          { type:"sell", name:"Rayane Bounida",      to:"Fayha",               date:"Juil. 2028", amount:"18,5M €"  },
          { type:"loan", name:"Paul Reverson",       to:"FC Volendam",         date:"Juil. 2028" },
          { type:"sell", name:"Pablo Solari",        to:"Ipswich",             date:"Juil. 2028", amount:"11,5M €"  },
          { type:"loan", name:"Marvyn Muzungu",      to:"Bournemouth",         date:"Juil. 2028" },
          { type:"sell", name:"Dominic Vincze",      to:"Real San Sebastián",  date:"Juil. 2028", amount:"13,25M €" },
          { type:"loan", name:"Damián van der Vaart", to:"FC Emmen",           date:"Juil. 2028" },
          { type:"loan", name:"Jorge Franco",        to:"Murcia",              date:"Juil. 2028" },
          { type:"loan", name:"Bence Polyák",        to:"Almere City",         date:"Juil. 2028" },
          { type:"loan", name:"Eloi Gómez",          to:"FC København",        date:"Aoû. 2028"  },
          { type:"loan", name:"Jordi de Bruijn",     to:"FC Emmen",            date:"Aoû. 2028"  },
          { type:"loan", name:"Sean Steur",          to:"QPR",                 date:"Aoû. 2028"  },
          { type:"loan", name:"Josip Šutalo",        to:"Bournemouth",         date:"Aoû. 2028"  },
          { type:"sell", name:"Pablo Campos",        to:"PSV",                 date:"Sep. 2028",  amount:"7,75M €"  },
          { type:"loan", name:"Ousmane Diao",        to:"Famalicão",           date:"Sep. 2028"  },
        ],
      },

      /* ─ Étape 2 : Chelsea FC ─ */
      {
        club:        "Chelsea FC",
        logo:        "logo-chelsea.png",
        accent:      "#2a6fdb",
        phase:       "DEUXIÈME PARTIE",
        tenure:      "Décembre 2028 → Mai 2029",
        league:      "Premier League",
        positionText:"Repris 15ᵉ · terminé 6ᵉ",
        record:      { played:21, wins:15, draws:3, losses:3, gf:45, ga:24 },
        note:        "Chelsea termine 6ᵉ et décroche une qualification pour l'UEFA Europa League.",

        matches: [
          { r:"W", tip:"Southampton (E) 1-3" },
          { r:"W", tip:"Everton (D) 5-2" },
          { r:"W", tip:"Bournemouth (E) 1-3" },
          { r:"W", tip:"Newcastle (E) 1-3" },
          { r:"W", tip:"Fulham (D) 2-0" },
          { r:"W", tip:"Crystal Palace (D) 3-0" },
          { r:"W", tip:"Nott'm Forest (D) 1-0" },
          { r:"L", tip:"Ipswich (E) 3-0" },
          { r:"D", tip:"Spurs (D) 1-1" },
          { r:"W", tip:"Leeds (E) 1-3" },
          { r:"W", tip:"Man Utd (E) 1-2" },
          { r:"L", tip:"Brentford (D) 0-1" },
          { r:"D", tip:"Aston Villa (D) 2-2" },
          { r:"D", tip:"Wolves (E) 0-0" },
          { r:"W", tip:"Everton (E) 1-4" },
          { r:"W", tip:"Southampton (D) 3-1" },
          { r:"W", tip:"Bournemouth (D) 4-1" },
          { r:"W", tip:"Man City (D) 1-0" },
          { r:"W", tip:"West Ham (E) 3-4" },
          { r:"W", tip:"Liverpool (D) 1-0" },
          { r:"L", tip:"Arsenal (E) 4-0" },
        ],

        cups: [
          {
            name:  "UEFA Champions League",
            phase: "Reprise en cours de phase · 18ᵉ (12 pts) → barrage franchi",
            rounds: [
              { result:"L", round:"J7",            score:"2-1", opponent:"Benfica (E)"            },
              { result:"D", round:"J8",            score:"0-0", opponent:"LOSC Lille (D)"         },
              { result:"W", round:"Barrage",       score:"3-2", opponent:"Bayern Munich (cumul)"  },
              { result:"L", round:"8e de finale",  score:"1-4", opponent:"Liverpool (cumul)"      },
            ],
          },
          {
            name: "Coupe d'Angleterre",
            rounds: [
              { result:"W", round:"3e tour", score:"0-1",        opponent:"Leeds (E)"        },
              { result:"W", round:"4e tour", score:"1-0",        opponent:"Cardiff (D)"      },
              { result:"L", round:"5e tour", score:"1-0 t.a.b.", opponent:"Southampton (E)"  },
            ],
          },
          {
            name: "Carabao Cup",
            rounds: [
              { result:"L", round:"Quart", score:"4-0", opponent:"Man City (E)" },
            ],
          },
        ],

        scorers: [
          { name:"Nico Williams", detail:"AG · Espagnol · 26 ans",  value:19 },
          { name:"João Pedro",    detail:"MOC · Brésilien · 27 ans", value:12 },
          { name:"Estêvão",       detail:"AD · Brésilien · 22 ans",  value:11 },
        ],
        assists: [
          { name:"Marc Cucurella",        detail:"DG · Espagnol · 30 ans",         value:11 },
          { name:"Estêvão / João Pedro",  detail:"AD / MOC · Ex-aequo",            value:9  },
          { name:"Alexis Mac Allister",   detail:"MC · Argentin · 30 ans · Prêt",  value:8  },
        ],
        ratings: [
          { name:"Marc Cucurella",  detail:"DG · Espagnol · 30 ans · 11 passes D.", value:7.15 },
          { name:"Enzo Fernández",  detail:"MC · Argentin · 28 ans · 7 buts",       value:7.08 },
          { name:"Nico Williams",   detail:"AG · Espagnol · 26 ans · 19 buts",      value:7.06 },
        ],

        transfers: [
          { type:"buy", name:"Can Uzun",        from:"Eintracht Frankfurt", date:"Jan. 2029", amount:"39M €" },
          { type:"buy", name:"Lucas Chevalier", from:"Paris SG",            date:"Jan. 2029", amount:"55M €" },
        ],
        departures: [
          { type:"free", name:"Cody Roberts",     to:"Sunderland",  date:"Jan. 2029" },
          { type:"loan", name:"Dastan Sätpayev",  to:"Leicester",   date:"Jan. 2029" },
          { type:"sell", name:"Dante Waite",      to:"Birmingham",  date:"Jan. 2029", amount:"350K €"  },
          { type:"loan", name:"Marc Guiu",        to:"Albacete",    date:"Jan. 2029" },
          { type:"sell", name:"Lewi Richards",    to:"Sunderland",  date:"Jan. 2029", amount:"400K €"  },
          { type:"loan", name:"Geovany Quenda",   to:"Leicester",   date:"Jan. 2029" },
          { type:"sell", name:"Cole Palmer",      to:"Barcelone",   date:"Jan. 2029", amount:"115M €"  },
          { type:"sell", name:"Dennis Seimen",    to:"Paris SG",    date:"Jan. 2029", amount:"68M €"   },
          { type:"loan", name:"Matthew Nketia",   to:"Oxford United", date:"Fév. 2029" },
        ],

        standings: [
          { pos:1,  team:"Man City",       j:38, g:24, n:9,  l:5,  bp:79, bc:36, db: 43, pts:81, zone:"promo" },
          { pos:2,  team:"Liverpool",      j:38, g:23, n:9,  l:6,  bp:67, bc:30, db: 37, pts:78, zone:"promo" },
          { pos:3,  team:"Newcastle",      j:38, g:24, n:6,  l:8,  bp:68, bc:39, db: 29, pts:78, zone:"promo" },
          { pos:4,  team:"Arsenal",        j:38, g:24, n:5,  l:9,  bp:74, bc:33, db: 41, pts:77, zone:"promo" },
          { pos:5,  team:"Spurs",          j:38, g:22, n:7,  l:9,  bp:65, bc:45, db: 20, pts:73 },
          { pos:6,  team:"Chelsea",        j:38, g:20, n:7,  l:11, bp:66, bc:46, db: 20, pts:67, highlight:true },
          { pos:7,  team:"Man Utd",        j:38, g:16, n:8,  l:14, bp:45, bc:42, db:  3, pts:56 },
          { pos:8,  team:"Crystal Palace", j:38, g:15, n:8,  l:15, bp:47, bc:52, db: -5, pts:53 },
          { pos:9,  team:"Wolves",         j:38, g:14, n:10, l:14, bp:41, bc:42, db: -1, pts:52 },
          { pos:10, team:"Brentford",      j:38, g:13, n:12, l:13, bp:49, bc:56, db: -7, pts:51 },
          { pos:11, team:"West Ham",       j:38, g:14, n:6,  l:18, bp:50, bc:65, db:-15, pts:48 },
          { pos:12, team:"Nott'm Forest",  j:38, g:12, n:11, l:15, bp:46, bc:50, db: -4, pts:47 },
          { pos:13, team:"Leeds",          j:38, g:14, n:4,  l:20, bp:48, bc:64, db:-16, pts:46 },
          { pos:14, team:"Aston Villa",    j:38, g:10, n:14, l:14, bp:52, bc:49, db:  3, pts:44 },
          { pos:15, team:"Brighton",       j:38, g:10, n:14, l:14, bp:55, bc:62, db: -7, pts:44 },
          { pos:16, team:"Bournemouth",    j:38, g:8,  n:12, l:18, bp:42, bc:67, db:-25, pts:36 },
          { pos:17, team:"Everton",        j:38, g:8,  n:10, l:20, bp:35, bc:62, db:-27, pts:34 },
          { pos:18, team:"Fulham",         j:38, g:7,  n:10, l:21, bp:42, bc:62, db:-20, pts:31, zone:"releg" },
          { pos:19, team:"Ipswich",        j:38, g:8,  n:7,  l:23, bp:34, bc:71, db:-37, pts:31, zone:"releg" },
          { pos:20, team:"Southampton",    j:38, g:6,  n:7,  l:25, bp:35, bc:67, db:-32, pts:25, zone:"releg" },
        ],
        relegated: ["Fulham", "Ipswich", "Southampton"],
      },
    ],
  },


  /* ─── SAISON 2029/30 · CHELSEA FC (1ʳᵉ saison pleine) ─── */
  {
    id:         "ajax-2029-30",
    year:       "2029/30",
    league:     "Premier League",
    position:   6,
    totalTeams: 20,
    points:     64,
    played:     38,
    wins:       19,
    draws:      7,
    losses:     12,
    gf:         85,
    ga:         65,

    splash: {
      eyebrow:  "2029/30 · Chelsea FC · Saison 5",
      lines:    ["SIXIÈMES.", "ENCORE L'EUROPE."],
      sub:      "Premier League · 6ᵉ · 64 pts · Qualifié en Europa League",
      tagline:  "Première saison pleine à Stamford Bridge : 85 buts, un Estêvão de gala, et une épopée européenne stoppée en 8ᵉ par le PSV. Chelsea repart en Europa League.",
    },

    scorers: [
      { name:"Estêvão",                  detail:"AD · Brésilien · toutes comp.",      value:17 },
      { name:"João Pedro",               detail:"MOC · Brésilien · toutes comp.",     value:16 },
      { name:"Nico Williams · Can Uzun", detail:"AG / MOC · ex-aequo · toutes comp.", value:13 },
    ],
    assists: [],
    ratings: [],

    matches: [
      { r:"W", tip:"Bournemouth (E) 0-3"     },
      { r:"L", tip:"Man City (D) 0-1"        },
      { r:"L", tip:"Nott'm Forest (E) 3-1"   },
      { r:"W", tip:"Norwich (D) 4-2"         },
      { r:"W", tip:"Crystal Palace (D) 4-1"  },
      { r:"L", tip:"Newcastle (E) 3-2"       },
      { r:"L", tip:"Spurs (D) 0-4"           },
      { r:"D", tip:"West Ham (E) 2-2"        },
      { r:"W", tip:"Leicester (E) 2-4"       },
      { r:"L", tip:"Liverpool (D) 1-2"       },
      { r:"D", tip:"Leeds (E) 0-0"           },
      { r:"W", tip:"Aston Villa (E) 0-4"     },
      { r:"L", tip:"Man Utd (D) 1-2"         },
      { r:"W", tip:"Sunderland (D) 5-1"      },
      { r:"L", tip:"Arsenal (E) 3-0"         },
      { r:"W", tip:"Brentford (D) 2-1"       },
      { r:"W", tip:"Everton (E) 2-3"         },
      { r:"D", tip:"Brighton (D) 2-2"        },
      { r:"W", tip:"Wolves (E) 1-3"          },
      { r:"W", tip:"Nott'm Forest (D) 5-1"   },
      { r:"D", tip:"Norwich (E) 2-2"         },
      { r:"W", tip:"Crystal Palace (E) 1-3"  },
      { r:"L", tip:"Man City (E) 6-0"        },
      { r:"W", tip:"Bournemouth (D) 3-2"     },
      { r:"W", tip:"Newcastle (D) 5-2"       },
      { r:"D", tip:"West Ham (D) 1-1"        },
      { r:"L", tip:"Man Utd (E) 3-1"         },
      { r:"W", tip:"Sunderland (E) 1-3"      },
      { r:"W", tip:"Aston Villa (D) 2-1"     },
      { r:"L", tip:"Arsenal (D) 1-3"         },
      { r:"W", tip:"Wolves (D) 5-1"          },
      { r:"L", tip:"Brighton (E) 2-0"        },
      { r:"L", tip:"Everton (D) 1-3"         },
      { r:"W", tip:"Leicester (D) 5-0"       },
      { r:"W", tip:"Brentford (E) 1-2"       },
      { r:"W", tip:"Liverpool (E) 2-4"       },
      { r:"D", tip:"Leeds (D) 0-0"           },
      { r:"D", tip:"Spurs (E) 1-1"           },
    ],

    cup2: {
      name: "UEFA Europa League",
      phase: "Phase de championnat : 10ᵉ/36 · qualifié au barrage · éliminé en 8ᵉ par le PSV (cumul 6-5)",
      rounds: [
        { result:"L", round:"J1",          score:"1-3", opponent:"PSV Eindhoven (D)"      },
        { result:"W", round:"J2",          score:"3-0", opponent:"Beşiktaş (D)"           },
        { result:"D", round:"J3",          score:"2-2", opponent:"AEK Athènes (E)"        },
        { result:"D", round:"J4",          score:"2-2", opponent:"Celta Vigo (E)"         },
        { result:"L", round:"J5",          score:"3-2", opponent:"Milan (E)"              },
        { result:"W", round:"J6",          score:"0-4", opponent:"Rennes (E)"             },
        { result:"W", round:"J7",          score:"5-1", opponent:"Panionios (D)"          },
        { result:"W", round:"J8",          score:"9-0", opponent:"Hapoel Be'er Sheva (D)" },
        { result:"W", round:"Barrage A",   score:"2-6", opponent:"Rapid Wien (E)"         },
        { result:"D", round:"Barrage R",   score:"3-3", opponent:"Rapid Wien (D) — qual. 9-5" },
        { result:"W", round:"8e A",        score:"5-4", opponent:"PSV Eindhoven (D)"      },
        { result:"L", round:"8e R",        score:"2-0", opponent:"PSV Eindhoven (E) — élim. 6-5" },
      ],
    },

    cups: [
      {
        name: "Carabao Cup",
        rounds: [
          { result:"W", round:"3e tour", score:"0-2", opponent:"Bolton (E)"   },
          { result:"W", round:"4e tour", score:"4-0", opponent:"MK Dons (D)"  },
          { result:"L", round:"Quart",   score:"2-0", opponent:"Man City (E)" },
        ],
      },
      {
        name: "FA Cup",
        rounds: [
          { result:"W", round:"3e tour", score:"3-1", opponent:"Stoke (D)"        },
          { result:"W", round:"4e tour", score:"0-3", opponent:"Fulham (E)"       },
          { result:"L", round:"5e tour", score:"6-2", opponent:"Ipswich Town (E)" },
        ],
      },
    ],

    elTable: [
      { pos:1,  team:"Milan",               j:8, g:7, n:1, l:0, bp:31, bc:9,  db:22, pts:22, zone:"promo" },
      { pos:2,  team:"Man Utd",             j:8, g:7, n:1, l:0, bp:23, bc:3,  db:20, pts:22, zone:"promo" },
      { pos:3,  team:"Nice",                j:8, g:7, n:1, l:0, bp:14, bc:5,  db:9,  pts:22, zone:"promo" },
      { pos:4,  team:"PSV Eindhoven",       j:8, g:6, n:1, l:1, bp:23, bc:5,  db:18, pts:19, zone:"promo" },
      { pos:5,  team:"Real Sociedad",       j:8, g:6, n:1, l:1, bp:18, bc:9,  db:9,  pts:19, zone:"promo" },
      { pos:6,  team:"Braga",               j:8, g:6, n:1, l:1, bp:13, bc:5,  db:8,  pts:19, zone:"promo" },
      { pos:7,  team:"Atalanta",            j:8, g:5, n:1, l:2, bp:18, bc:5,  db:13, pts:16, zone:"promo" },
      { pos:8,  team:"Bayer Leverkusen",    j:8, g:5, n:1, l:2, bp:19, bc:12, db:7,  pts:16, zone:"promo" },
      { pos:9,  team:"Beşiktaş",            j:8, g:5, n:0, l:3, bp:14, bc:11, db:3,  pts:15 },
      { pos:10, team:"Chelsea",             j:8, g:4, n:2, l:2, bp:28, bc:11, db:17, pts:14, highlight:true },
      { pos:11, team:"Sivasspor",           j:8, g:4, n:2, l:2, bp:17, bc:7,  db:10, pts:14 },
      { pos:12, team:"Celta Vigo",          j:8, g:4, n:2, l:2, bp:16, bc:8,  db:8,  pts:14 },
      { pos:13, team:"Eintracht Frankfurt", j:8, g:4, n:2, l:2, bp:17, bc:15, db:2,  pts:14 },
      { pos:14, team:"Rangers",             j:8, g:4, n:1, l:3, bp:22, bc:7,  db:15, pts:13 },
      { pos:15, team:"FC Midtjylland",      j:8, g:4, n:1, l:3, bp:17, bc:11, db:6,  pts:13 },
      { pos:16, team:"Galatasaray SK",      j:8, g:4, n:1, l:3, bp:14, bc:11, db:3,  pts:13 },
      { pos:17, team:"Red Bull Salzburg",   j:8, g:4, n:1, l:3, bp:12, bc:13, db:-1, pts:13 },
      { pos:18, team:"Rennes",              j:8, g:3, n:3, l:2, bp:17, bc:10, db:7,  pts:12 },
      { pos:19, team:"AEK Athènes",         j:8, g:3, n:3, l:2, bp:12, bc:12, db:0,  pts:12 },
      { pos:20, team:"Olympiacos",          j:8, g:3, n:2, l:3, bp:15, bc:17, db:-2, pts:11 },
      { pos:21, team:"Monaco",              j:8, g:3, n:2, l:3, bp:7,  bc:9,  db:-2, pts:11 },
      { pos:22, team:"Rapid Wien",          j:8, g:2, n:3, l:3, bp:10, bc:9,  db:1,  pts:9  },
      { pos:23, team:"APOEL",               j:8, g:3, n:0, l:5, bp:12, bc:20, db:-8, pts:9  },
      { pos:24, team:"Brann",               j:8, g:2, n:2, l:4, bp:12, bc:12, db:0,  pts:8  },
      { pos:25, team:"Basel",               j:8, g:2, n:2, l:4, bp:10, bc:12, db:-2, pts:8,  zone:"releg" },
      { pos:26, team:"Viktoria Plzeň",      j:8, g:2, n:2, l:4, bp:6,  bc:8,  db:-2, pts:8,  zone:"releg" },
      { pos:27, team:"Gent",                j:8, g:2, n:1, l:5, bp:8,  bc:16, db:-8, pts:7,  zone:"releg" },
    ],

    transfers: [
      { type:"buy",  name:"Désiré Doué",              from:"Paris SG",       date:"Été 2029", amount:"177M €"  },
      { type:"buy",  name:"Eli Junior Kroupi",        from:"Feyenoord",      date:"Été 2029", amount:"140M €"  },
      { type:"buy",  name:"Christian Pulisic",        from:"Milan",          date:"Été 2029", amount:"50M €"   },
      { type:"buy",  name:"Aaron Hickey",             from:"Brentford",      date:"Été 2029", amount:"49,5M €" },
      { type:"buy",  name:"Joshua Kimmich",           from:"Bayern",         date:"Été 2029", amount:"17,25M €"},
      { type:"buy",  name:"Mahd Fadzil Abdul Karim",  from:"Aston Villa",    date:"Été 2029", amount:"10,5M €" },
      { type:"buy",  name:"Dequinho",                 from:"Flamengo",       date:"Été 2029", amount:"8,75M €" },
      { type:"buy",  name:"Tiago Pereira Cardoso",    from:"Juventus",       date:"Été 2029", amount:"500K €"  },
      { type:"loan", name:"Manuel Ugarte",            from:"Man Utd",        date:"Été 2029" },
      { type:"loan", name:"Gabriel Pirani",           from:"Burnley",        date:"Été 2029" },
    ],
    departures: [
      { type:"sell", name:"Alejandro Garnacho",     to:"Barcelona",         date:"Été 2029", amount:"96M €"   },
      { type:"sell", name:"Reece James",            to:"Arsenal",           date:"Été 2029", amount:"82M €"   },
      { type:"sell", name:"Wesley Fofana",          to:"Paris SG",          date:"Été 2029", amount:"75M €"   },
      { type:"sell", name:"Aaron Anselmino",        to:"Bayern München",    date:"Été 2029", amount:"60M €"   },
      { type:"sell", name:"Malo Gusto",             to:"Napoli",            date:"Été 2029", amount:"29,5M €" },
      { type:"sell", name:"Filip Jorgensen",        to:"Atalanta",          date:"Été 2029", amount:"26M €"   },
      { type:"sell", name:"Mykhaylo Mudryk",        to:"West Ham",          date:"Été 2029", amount:"13,25M €"},
      { type:"sell", name:"Andrey Santos",          to:"Al-Fateh",          date:"Été 2029", amount:"11,75M €"},
      { type:"sell", name:"Simone Pafundi",         to:"Strasbourg",        date:"Été 2029", amount:"10,25M €"},
      { type:"sell", name:"Mamadou Sarr",           to:"Wolfsburg",         date:"Été 2029", amount:"7,25M €" },
      { type:"sell", name:"Luiz Henrique",          to:"Al Taawoun",        date:"Été 2029", amount:"3,2M €"  },
      { type:"sell", name:"Lee Lewis",              to:"Fulham",            date:"Été 2029", amount:"625K €"  },
      { type:"sell", name:"Greg Healy",             to:"Bournemouth",       date:"Été 2029", amount:"450K €"  },
      { type:"sell", name:"Izan Lawson",            to:"Brighton",          date:"Été 2029", amount:"375K €"  },
      { type:"sell", name:"Charlie Holland",        to:"Man Utd",           date:"Été 2029", amount:"325K €"  },
      { type:"sell", name:"Luke Bennett",           to:"Sunderland",        date:"Été 2029", amount:"300K €"  },
      { type:"sell", name:"Fernando Obregon",       to:"West Brom",         date:"Été 2029", amount:"150K €"  },
      { type:"loan", name:"Sidiki Chérif",          to:"Milan",             date:"Été 2029" },
      { type:"loan", name:"Liam Delap",             to:"Napoli",            date:"Été 2029" },
      { type:"loan", name:"Roméo Lavia",            to:"Sunderland",        date:"Été 2029" },
      { type:"loan", name:"Robert Sanchez",         to:"Udinese",           date:"Été 2029" },
      { type:"loan", name:"Christos Mandas",        to:"Lazio",             date:"Été 2029" },
      { type:"loan", name:"Tyler Dibling",          to:"Newcastle",         date:"Été 2029" },
      { type:"loan", name:"Ryan Kavuma-McQueen",    to:"Stuttgart",         date:"Été 2029" },
      { type:"loan", name:"Gabriel Carvalho",       to:"Sheffield United",  date:"Été 2029" },
      { type:"loan", name:"Caleb Wiley",            to:"Derby County",      date:"Été 2029" },
      { type:"loan", name:"Kendry Paez",            to:"West Brom",         date:"Été 2029" },
      { type:"loan", name:"Daston Sätpayev",        to:"Ipswich Town",      date:"Été 2029" },
      { type:"loan", name:"Shumaira Mheuka",        to:"Blackburn",         date:"Été 2029" },
      { type:"loan", name:"Mathis Eboué",           to:"Lyon",              date:"Été 2029" },
      { type:"loan", name:"Tommy Setford",          to:"Sparta Rotterdam",  date:"Été 2029" },
      { type:"loan", name:"Ishé Samuels-Smith",     to:"MK Dons",           date:"Été 2029" },
      { type:"loan", name:"Ibrahim Rabbaj",         to:"Raja Casablanca",   date:"Été 2029" },
      { type:"loan", name:"Matthew Nketia",         to:"Port Vale",         date:"Été 2029" },
      { type:"loan", name:"Yisa Alao",              to:"Reading",           date:"Été 2029" },
      { type:"loan", name:"Slaven Mrvaljevic",      to:"Charlton",          date:"Été 2029" },
      { type:"loan", name:"Omari Kellyman",         to:"Crewe",             date:"Été 2029" },
      { type:"loan", name:"Dequinho",               to:"PSV Eindhoven",     date:"Été 2029" },
      { type:"loan", name:"Mahd Fadzil Abdul Karim",to:"Oxford United",     date:"Été 2029" },
      { type:"loan", name:"Chizzy Ezewata",         to:"West Brom",         date:"Été 2029" },
      { type:"loan", name:"Chizzy Ezewata",         to:"FC Köln",           date:"Hiver 2030" },
      { type:"free", name:"Rubén Neves",            to:"Roma",              date:"Été 2029" },
      { type:"free", name:"Chris Atherton",         to:"Sunderland",        date:"Été 2029" },
      { type:"free", name:"Jacob Hall",             to:"Leicester",         date:"Été 2029" },
    ],

    standings: null,
  },
]

// Saisons à deux clubs : agrège le mercato des étapes au niveau saison (pour mercato.html)
;(window.SEASONS_ajax || []).forEach(function(s) {
  if (s.stints && !s.transfers)  s.transfers  = s.stints.reduce(function(a,st){ return a.concat(st.transfers  || []) }, [])
  if (s.stints && !s.departures) s.departures = s.stints.reduce(function(a,st){ return a.concat(st.departures || []) }, [])
})
