/**
 * ═══════════════════════════════════════════════════════════
 *  SEVILLA FC — DONNÉES DES SAISONS
 * ═══════════════════════════════════════════════════════════
 */
window.SEASONS_seville = [

  /* ─── SAISON 2025/26 ─────────────────────────────────── */
  {
    id: "seville-2025-26",
    year:       "2025/26",
    league:     "La Liga",
    position:   3,
    totalTeams: 20,
    points:     66,
    played:     38,
    wins:       19,
    draws:      9,
    losses:     10,
    gf:         78,
    ga:         51,
    promoted:   [],
    relegated:  ["Real Oviedo", "Levante", "Getafe"],

    scorers: [
      { name: "Isaac Romero",  detail: "BU · Espagnol · 26 ans",  value: 30 },
      { name: "Peque",         detail: "MOC · Espagnol · 23 ans", value: 20 },
      { name: "Akor Adams",    detail: "BU · Nigérian · 26 ans",  value: 9  },
    ],
    assists: [
      { name: "Juanlu / Rubén Vargas / Alfon", detail: "Ex-aequo",                value: 14 },
      { name: "Peque",                          detail: "MOC · Espagnol · 23 ans", value: 10 },
      { name: "Isaac Romero",                   detail: "BU · Espagnol · 26 ans",  value: 5  },
    ],
    ratings: [
      { name: "Isaac Romero",  detail: "BU · Espagnol · 26 ans",  value: 7.35 },
      { name: "Peque",         detail: "MOC · Espagnol · 23 ans", value: 7.29 },
      { name: "Gabriel Suazo", detail: "DG · Chilien · 28 ans",   value: 7.16 },
    ],

    transfers: [
      { type: "free", name: "Raf Vullers",    from: "Sans contrat", date: "Juil. 2025" },
      { type: "free", name: "Thomas Janssen", from: "Sans contrat", date: "Juil. 2025" },
    ],

    departures: [
      { type: "loan", name: "Ibra Sow",            to: "Mérida",            date: "Juil. 2025" },
      { type: "loan", name: "Thomas Janssen",       to: "Linares",           date: "Juil. 2025" },
      { type: "loan", name: "Raf Vullers",          to: "Malacitano",        date: "Juil. 2025" },
      { type: "loan", name: "Jorell",               to: "Xerez",             date: "Jan. 2026"  },
      { type: "loan", name: "Tomas Mendez",         to: "Xerez",             date: "Jan. 2026"  },
      { type: "loan", name: "Alexis Ciria",         to: "Castellon",         date: "Jan. 2026"  },
      { type: "loan", name: "Manu Bueno",           to: "Leganés",           date: "Jan. 2026"  },
      { type: "loan", name: "Edu Altozano",         to: "Las Palmas",        date: "Jan. 2026"  },
      { type: "loan", name: "Alberto Espiñeira",    to: "Rayo Majadahonda",  date: "Jan. 2026"  },
      { type: "loan", name: "Rayan Azaouagh",       to: "Xerez",             date: "Jan. 2026"  },
      { type: "loan", name: "Nico Guillén",         to: "Real Avilés",       date: "Jan. 2026"  },
    ],

    cup: {
      name: "Copa del Rey",
      rounds: [
        { result: "W", round: "1er tour",        score: "0 – 7",   opponent: "Ciudad Plasencia (E)"               },
        { result: "W", round: "2e tour",         score: "3 – 7 p", opponent: "Lorca Deportiva (E) — v. aux t.a.b" },
        { result: "W", round: "3e tour",         score: "0 – 8",   opponent: "Real Zaragoza (E)"                  },
        { result: "W", round: "4e tour",         score: "2 – 3",   opponent: "Villarreal (E)"                     },
        { result: "W", round: "Quart de finale", score: "3 – 0",   opponent: "Atlético de Madrid (D)"             },
        { result: "W", round: "½ finale aller",  score: "0 – 2",   opponent: "Real Valladolid (E)"                },
        { result: "W", round: "½ finale retour", score: "1 – 0",   opponent: "Real Valladolid (D)"                },
        { result: "L", round: "Finale",          score: "1 – 4",   opponent: "Real Madrid (N) — a.p."            },
      ],
    },

    playoffs: null,

    splash: {
      eyebrow:  "2025/26 · Sevilla FC · Saison 1",
      lines:    ["3e DE LA LIGA.", "FINALISTE."],
      sub:      "La Liga · 3e · 66 pts · Finale Copa del Rey",
      tagline:  "Séville frappe fort dès la première saison — jusqu'en finale contre le Real. 1-1 à la fin du temps réglementaire — le Real assomme en prolongation.",
    },

    matches: [
      { r:"W", tip:"Mallorca (E) 1-3"           },
      { r:"L", tip:"Girona (D) 1-2"             },
      { r:"L", tip:"Real Madrid (E) 6-1"        },
      { r:"W", tip:"Levante (D) 4-2"            },
      { r:"D", tip:"Real Betis (E) 1-1"         },
      { r:"W", tip:"Athletic Club (D) 2-1"      },
      { r:"L", tip:"Barcelona (E) 1-0"          },
      { r:"W", tip:"Osasuna (D) 3-2"            },
      { r:"L", tip:"Celta Vigo (E) 1-0"         },
      { r:"W", tip:"Elche (D) 4-0"              },
      { r:"W", tip:"Real Oviedo (E) 0-1"        },
      { r:"D", tip:"Alavés (D) 2-2"             },
      { r:"W", tip:"Atlético de Madrid (E) 0-1" },
      { r:"D", tip:"Valencia (D) 2-2"           },
      { r:"W", tip:"Espanyol (D) 5-0"           },
      { r:"W", tip:"Real Sociedad (E) 1-4"      },
      { r:"L", tip:"Rayo Vallecano (D) 1-2"     },
      { r:"W", tip:"Getafe (E) 0-3"             },
      { r:"W", tip:"Villarreal (D) 4-2"         },
      { r:"D", tip:"Girona (E) 2-2"             },
      { r:"L", tip:"Mallorca (D) 2-3"           },
      { r:"W", tip:"Real Madrid (D) 1-0"        },
      { r:"W", tip:"Levante (E) 1-2"            },
      { r:"W", tip:"Real Betis (D) 1-0"         },
      { r:"L", tip:"Athletic Club (E) 2-1"      },
      { r:"D", tip:"Barcelona (D) 0-0"          },
      { r:"D", tip:"Osasuna (E) 1-1"            },
      { r:"W", tip:"Celta Vigo (D) 4-2"         },
      { r:"W", tip:"Elche (E) 1-3"              },
      { r:"D", tip:"Real Oviedo (D) 1-1"        },
      { r:"L", tip:"Alavés (E) 1-0"             },
      { r:"W", tip:"Atlético de Madrid (D) 7-1" },
      { r:"D", tip:"Valencia (E) 1-1"           },
      { r:"L", tip:"Espanyol (E) 4-0"           },
      { r:"W", tip:"Real Sociedad (D) 3-0"      },
      { r:"D", tip:"Rayo Vallecano (E) 1-1"     },
      { r:"W", tip:"Getafe (D) 3-0"             },
      { r:"L", tip:"Villarreal (E) 4-3"         },
    ],

    standings: [
      { pos:1,  team:"Barcelona",          j:38, g:30, n:5,  l:3,  bp:100, bc:27, db: 73, pts:95, zone:"promo" },
      { pos:2,  team:"Real Madrid",        j:38, g:29, n:5,  l:4,  bp:100, bc:34, db: 66, pts:92, zone:"promo" },
      { pos:3,  team:"Sevilla",            j:38, g:19, n:9,  l:10, bp:78,  bc:51, db: 27, pts:66, zone:"promo", highlight:true },
      { pos:4,  team:"Mallorca",           j:38, g:20, n:4,  l:14, bp:58,  bc:47, db: 11, pts:64, zone:"promo" },
      { pos:5,  team:"Real Betis",         j:38, g:18, n:9,  l:11, bp:54,  bc:53, db:  1, pts:63              },
      { pos:6,  team:"Rayo Vallecano",     j:38, g:17, n:8,  l:13, bp:51,  bc:43, db:  8, pts:59              },
      { pos:7,  team:"Atlético de Madrid", j:38, g:15, n:13, l:10, bp:44,  bc:44, db:  0, pts:58              },
      { pos:8,  team:"Espanyol",           j:38, g:14, n:11, l:13, bp:52,  bc:53, db: -1, pts:53              },
      { pos:9,  team:"Girona",             j:38, g:14, n:8,  l:16, bp:55,  bc:57, db: -2, pts:50              },
      { pos:10, team:"Alavés",             j:38, g:13, n:11, l:14, bp:41,  bc:47, db: -6, pts:50              },
      { pos:11, team:"Athletic Club",      j:38, g:14, n:6,  l:18, bp:49,  bc:56, db: -7, pts:48              },
      { pos:12, team:"Osasuna",            j:38, g:12, n:11, l:15, bp:52,  bc:58, db: -6, pts:47              },
      { pos:13, team:"Celta Vigo",         j:38, g:13, n:8,  l:17, bp:44,  bc:50, db: -6, pts:47              },
      { pos:14, team:"Valencia",           j:38, g:11, n:12, l:15, bp:53,  bc:54, db: -1, pts:45              },
      { pos:15, team:"Real Sociedad",      j:38, g:12, n:8,  l:18, bp:49,  bc:64, db:-15, pts:44              },
      { pos:16, team:"Elche",              j:38, g:11, n:11, l:16, bp:44,  bc:62, db:-18, pts:44              },
      { pos:17, team:"Villarreal",         j:38, g:11, n:8,  l:19, bp:36,  bc:55, db:-19, pts:41              },
      { pos:18, team:"Real Oviedo",        j:38, g:11, n:7,  l:20, bp:39,  bc:68, db:-29, pts:40, zone:"releg" },
      { pos:19, team:"Levante",            j:38, g:6,  n:8,  l:24, bp:44,  bc:86, db:-42, pts:26, zone:"releg" },
      { pos:20, team:"Getafe",             j:38, g:7,  n:4,  l:27, bp:22,  bc:56, db:-34, pts:25, zone:"releg" },
    ],
  },

  /* ─── SAISON 2026/27 ─────────────────────────────────── */
  {
    id:         "seville-2026-27",
    year:       "2026/27",
    league:     "La Liga",
    position:   4,
    totalTeams: 20,
    points:     70,
    played:     38,
    wins:       19,
    draws:      13,
    losses:     6,
    gf:         76,
    ga:         38,
    promoted:   [],
    relegated:  ["Osasuna", "Athletic Club", "Real Zaragoza"],

    scorers: [
      { name: "Isaac Romero",  detail: "BU · Espagnol · 27 ans",  value: 29 },
      { name: "Peque",         detail: "MOC · Espagnol · 24 ans", value: 14 },
      { name: "Alfon",         detail: "AG · Espagnol · 28 ans",  value: 12 },
    ],
    assists: [
      { name: "Juanlu",        detail: "ALD · Espagnol · 23 ans", value: 20 },
      { name: "Peque",         detail: "MOC · Espagnol · 24 ans", value: 18 },
      { name: "Rubén Vargas",  detail: "AG · Suisse · 28 ans",    value: 13 },
    ],
    ratings: [
      { name: "Juanlu",        detail: "ALD · Espagnol · 23 ans", value: 7.20 },
      { name: "Peque",         detail: "MOC · Espagnol · 24 ans", value: 7.19 },
      { name: "Alfon",         detail: "AG · Espagnol · 28 ans",  value: 7.16 },
    ],

    transfers: [
      { type: "sell", name: "Odysseas Vlachodimos", from: "Newcastle",  date: "Juil. 2026", amount: "19,75M €" },
      { type: "free", name: "Modibo Sissoko",        from: "Guidars FC", date: "Juil. 2026"                    },
      { type: "loan", name: "Lucas Cañizares",       from: "Tondela",    date: "Juil. 2026"                    },
    ],

    departures: [
      { type: "sell", name: "Alvaro Fernandez",     to: "Ajax",              date: "Juil. 2026", amount: "5,75M €" },
      { type: "free", name: "Adnan Januzaj",         to: "West Brom",         date: "Juil. 2026"                    },
      { type: "sell", name: "Federico Gattoni",      to: "Al Nijmeh",         date: "Juil. 2026", amount: "2,4M €"  },
      { type: "loan", name: "Chidera Ejuke",         to: "AZ",                date: "Juil. 2026"                    },
      { type: "sell", name: "Andrés Castrin",        to: "Elche",             date: "Juil. 2026", amount: "1,8M €"  },
      { type: "free", name: "Alexis Sanchez",        to: "ATM",               date: "Juil. 2026"                    },
      { type: "free", name: "Sergio Pascual",        to: "Real Zaragoza",     date: "Juil. 2026"                    },
      { type: "sell", name: "Orjan Nyland",          to: "Cagliari",          date: "Juil. 2026", amount: "2,6M €"  },
      { type: "loan", name: "José Manuel Castro",    to: "Malacitano",        date: "Juil. 2026"                    },
      { type: "loan", name: "Jorge",                 to: "Eldense",           date: "Juil. 2026"                    },
      { type: "loan", name: "Rayan Azaouagh",        to: "Xerez",             date: "Juil. 2026"                    },
      { type: "loan", name: "Alberto Espiñeira",     to: "Ibiza",             date: "Juil. 2026"                    },
      { type: "loan", name: "Marcão",                to: "Celta Vigo",        date: "Jan. 2027"                     },
      { type: "loan", name: "Fabio Cardoso",         to: "Eibar",             date: "Jan. 2027"                     },
      { type: "loan", name: "Adria Pedrosa",         to: "Aston Villa",       date: "Jan. 2027"                     },
      { type: "loan", name: "Ramon",                 to: "Nice",              date: "Jan. 2027"                     },
      { type: "loan", name: "Jordi Diez",            to: "Tudelano",          date: "Jan. 2027"                     },
      { type: "loan", name: "Alvaro Valencia",       to: "Real Union",        date: "Jan. 2027"                     },
      { type: "loan", name: "Javier Abumgono",       to: "San Félix",         date: "Jan. 2027"                     },
      { type: "loan", name: "Héctor Gonzalez",       to: "Eldense",           date: "Jan. 2027"                     },
      { type: "loan", name: "Alex Moron",            to: "Coruxo",            date: "Jan. 2027"                     },
    ],

    cup: {
      name: "Copa del Rey",
      rounds: [
        { result: "W", round: "3e tour", score: "1 – 3", opponent: "Malacitano (E)" },
        { result: "L", round: "4e tour", score: "5 – 2", opponent: "Almería (E)"    },
      ],
    },

    cup2: {
      name: "UEFA Champions League",
      phase: "Phase de championnat : 10e · 5V 2N 1D · 12 pts → Barrage",
      rounds: [
        { result: "W", round: "Barrage A",  score: "0 – 3",  opponent: "Milan (E)"        },
        { result: "W", round: "Barrage R",  score: "2 – 2",  opponent: "Milan (D) — 5-2"  },
        { result: "W", round: "1/8 A",      score: "1 – 1",  opponent: "Lille (D)"        },
        { result: "W", round: "1/8 R",      score: "1 – 3",  opponent: "Lille (E) — 4-2"  },
        { result: "L", round: "QF aller",   score: "1 – 2",  opponent: "Aston Villa (D)"  },
        { result: "L", round: "QF retour",  score: "2 – 2",  opponent: "Aston Villa (E) — 3-4" },
      ],
    },

    playoffs: null,

    splash: {
      eyebrow:  "2026/27 · Sevilla FC · Saison 2",
      lines:    ["LIGUE DES", "CHAMPIONS."],
      sub:      "La Liga · 4e · 70 pts · Quart de finale UCL",
      tagline:  "Séville s'invite parmi l'élite européenne — éliminé de justesse par Aston Villa après avoir sorti Milan et Lille.",
    },

    matches: [
      { r:"W", tip:"Real Zaragoza (E) 0-3"        },
      { r:"W", tip:"Elche (D) 5-0"                },
      { r:"W", tip:"Real Sociedad (E) 0-1"         },
      { r:"L", tip:"Barcelona (D) 0-3"             },
      { r:"W", tip:"Real Betis (E) 1-2"            },
      { r:"L", tip:"Atlético de Madrid (D) 0-1"    },
      { r:"D", tip:"Alavés (E) 1-1"                },
      { r:"D", tip:"Celta Vigo (D) 0-0"            },
      { r:"L", tip:"Valencia (E) 2-0"              },
      { r:"D", tip:"Girona (D) 2-2"                },
      { r:"W", tip:"Villarreal (E) 0-2"            },
      { r:"W", tip:"Mallorca (D) 2-1"              },
      { r:"W", tip:"Athletic Club (E) 1-3"         },
      { r:"W", tip:"Espanyol (D) 4-1"              },
      { r:"D", tip:"Osasuna (D) 2-2"               },
      { r:"L", tip:"Real Madrid (E) 4-0"           },
      { r:"W", tip:"Cádiz (D) 5-0"                 },
      { r:"D", tip:"Sporting Gijón (E) 0-0"        },
      { r:"W", tip:"Rayo Vallecano (D) 2-0"        },
      { r:"W", tip:"Elche (E) 2-6"                 },
      { r:"L", tip:"Real Zaragoza (D) 1-2"         },
      { r:"D", tip:"Real Sociedad (D) 1-1"         },
      { r:"D", tip:"Barcelona (E) 0-0"             },
      { r:"W", tip:"Real Betis (D) 3-0"            },
      { r:"D", tip:"Atlético de Madrid (E) 2-2"    },
      { r:"L", tip:"Alavés (D) 0-1"                },
      { r:"D", tip:"Celta Vigo (E) 1-1"            },
      { r:"W", tip:"Valencia (D) 3-2"              },
      { r:"W", tip:"Girona (E) 1-4"                },
      { r:"D", tip:"Villarreal (D) 1-1"            },
      { r:"W", tip:"Mallorca (E) 2-3"              },
      { r:"D", tip:"Athletic Club (D) 1-1"         },
      { r:"W", tip:"Espanyol (E) 1-4"              },
      { r:"D", tip:"Osasuna (E) 0-0"               },
      { r:"D", tip:"Real Madrid (D) 1-1"           },
      { r:"W", tip:"Cádiz (E) 0-4"                 },
      { r:"W", tip:"Sporting Gijón (D) 4-0"        },
      { r:"W", tip:"Rayo Vallecano (E) 1-3"        },
    ],

    standings: [
      { pos:1,  team:"Real Madrid",        j:38, g:28, n:8,  l:2,  bp:98, bc:30, db: 68, pts:92, zone:"promo" },
      { pos:2,  team:"Barcelona",          j:38, g:29, n:5,  l:4,  bp:99, bc:28, db: 71, pts:92, zone:"promo" },
      { pos:3,  team:"Atlético de Madrid", j:38, g:21, n:11, l:6,  bp:70, bc:35, db: 35, pts:74, zone:"promo" },
      { pos:4,  team:"Sevilla",            j:38, g:19, n:13, l:6,  bp:76, bc:38, db: 38, pts:70, zone:"promo", highlight:true },
      { pos:5,  team:"Real Betis",         j:38, g:17, n:8,  l:13, bp:53, bc:42, db: 11, pts:59              },
      { pos:6,  team:"Celta Vigo",         j:38, g:14, n:13, l:11, bp:46, bc:43, db:  3, pts:55              },
      { pos:7,  team:"Mallorca",           j:38, g:16, n:6,  l:16, bp:61, bc:68, db: -7, pts:54              },
      { pos:8,  team:"Girona",             j:38, g:12, n:17, l:9,  bp:57, bc:44, db: 13, pts:53              },
      { pos:9,  team:"Valencia",           j:38, g:13, n:10, l:15, bp:47, bc:48, db: -1, pts:49              },
      { pos:10, team:"Real Sociedad",      j:38, g:13, n:7,  l:18, bp:48, bc:61, db:-13, pts:46              },
      { pos:11, team:"Rayo Vallecano",     j:38, g:14, n:4,  l:20, bp:49, bc:64, db:-15, pts:46              },
      { pos:12, team:"Alavés",             j:38, g:11, n:10, l:17, bp:44, bc:57, db:-13, pts:43              },
      { pos:13, team:"Sporting Gijón",     j:38, g:12, n:6,  l:20, bp:53, bc:69, db:-16, pts:42              },
      { pos:14, team:"Espanyol",           j:38, g:11, n:8,  l:19, bp:47, bc:76, db:-29, pts:41              },
      { pos:15, team:"Villarreal",         j:38, g:10, n:11, l:17, bp:49, bc:58, db: -9, pts:41              },
      { pos:16, team:"Cádiz",              j:38, g:10, n:10, l:18, bp:37, bc:61, db:-24, pts:40              },
      { pos:17, team:"Elche",              j:38, g:9,  n:11, l:18, bp:44, bc:68, db:-24, pts:38              },
      { pos:18, team:"Osasuna",            j:38, g:8,  n:14, l:16, bp:36, bc:67, db:-31, pts:38, zone:"releg" },
      { pos:19, team:"Athletic Club",      j:38, g:8,  n:11, l:19, bp:39, bc:62, db:-23, pts:35, zone:"releg" },
      { pos:20, team:"Real Zaragoza",      j:38, g:8,  n:11, l:19, bp:34, bc:68, db:-34, pts:35, zone:"releg" },
    ],
  },

]
