/**
 * AJAX AMSTERDAM — DONNÉES DES SAISONS (Multi)
 */
window.SEASONS_ajax = [

  /* ─── SAISON 2025/26 ─────────────────────────────────── */
  {
    id:         "ajax-2025-26",
    year:       "2025/26",
    league:     "Eredivisie",
    position:   2,
    totalTeams: 18,
    points:     84,
    played:     34,
    wins:       27,
    draws:      3,
    losses:     4,
    gf:         108,
    ga:         39,
    promoted:   [],
    relegated:  ["NAC Breda", "sc Heerenveen", "Heracles Almelo"],

    scorers: [
      { name: "Kasper Dolberg", detail: "BU · Danois", value: 40 },
    ],
    assists:  [],
    ratings:  [],

    transfers: [
      { type: "loan", name: "Robin Hack",            from: "Gladbach",    date: "Été 2025"                  },
      { type: "loan", name: "Arnau Puigmal",          from: "Almeria",     date: "Été 2025"                  },
      { type: "free", name: "Romke van de Pol",       from: "Vitesse",     date: "Été 2025"                  },
      { type: "sell", name: "Nicolas de la Cruz",     from: "Flamengo",    date: "Été 2025", amount: "7,5M €" },
      { type: "sell", name: "Joël Schingtienne",     from: "Venezia",     date: "Été 2025", amount: "1,6M €" },
      { type: "sell", name: "Andrea Compagno",        from: "Jeonbuk",     date: "Été 2025", amount: "2M €"   },
      { type: "free", name: "Taiyo Koga",             from: "Kashiwa",     date: "Été 2025"                  },
      { type: "free", name: "Takahiro Ohgihara",      from: "Kobe",        date: "Été 2025"                  },
    ],

    departures: [
      { type: "loan", name: "Marouane Bentaleb",      to: "JS Soualem",     date: "Été 2025"                   },
      { type: "loan", name: "Zakaria Ouzane",          to: "Helmond Sport",  date: "Été 2025"                   },
      { type: "loan", name: "Niilo Tarvajarvi",        to: "Gnistan",        date: "Été 2025"                   },
      { type: "loan", name: "Jinairo Johnson",         to: "Vitesse",        date: "Été 2025"                   },
      { type: "sell", name: "Wout Weghorst",           to: "Al-Kholood",     date: "Été 2025", amount: "1M €"   },
      { type: "sell", name: "Davy Klaassen",           to: "AEK Athènes",    date: "Été 2025", amount: "1,8M €" },
      { type: "sell", name: "Anton Gaaei",             to: "Atalanta",       date: "Été 2025", amount: "5,25M €"},
      { type: "loan", name: "Maher Carrizo",           to: "Wrexham",        date: "Été 2025"                   },
      { type: "sell", name: "Tijn Peters",             to: "Twente",         date: "Été 2025", amount: "135K €" },
      { type: "sell", name: "Elias Mechrouch",         to: "N.E.C.",         date: "Été 2025", amount: "250K €" },
    ],

    cup: {
      name: "KNVB Beker",
      rounds: [
        { result: "W", round: "2e tour",  score: "0 – 3", opponent: "Sparta Rotterdam (E)" },
        { result: "L", round: "3e tour",  score: "2 – 4", opponent: "PSV (D)"              },
      ],
    },

    cup2: {
      name: "UEFA Champions League",
      phase: "Phase de championnat : 22e · 3V 0N 5D · 9 pts → Barrage · Éliminé par Bergame",
      rounds: [
        { result: "W", round: "Barrage A", score: "2 – 1", opponent: "Bergame (D)"              },
        { result: "L", round: "Barrage R", score: "4 – 2", opponent: "Bergame (E) — 4-5 éliminé" },
      ],
    },

    playoffs: null,

    splash: {
      eyebrow:  "2025/26 · Ajax Amsterdam · Saison 1",
      lines:    ["DOLBERG.", "40 BUTS."],
      sub:      "Eredivisie · 2e · 84 pts · UCL Barrage",
      tagline:  "Vice-champions derrière Feyenoord. Kasper Dolberg écrit l'histoire du club avec 40 buts en une saison.",
    },

    matches: [
      { r:"W", tip:"Telstar (D) 9-0"           },
      { r:"L", tip:"Go Ahead Eagles (E) 2-1"   },
      { r:"W", tip:"Heracles Almelo (D) 1-0"   },
      { r:"W", tip:"FC Volendam (E) 0-4"       },
      { r:"W", tip:"PEC Zwolle (D) 3-0"        },
      { r:"L", tip:"PSV (E) 3-2"               },
      { r:"W", tip:"NAC Breda (D) 6-0"         },
      { r:"W", tip:"Sparta Rotterdam (E) 1-3"  },
      { r:"D", tip:"AZ (D) 1-1"                },
      { r:"W", tip:"FC Twente (E) 0-2"         },
      { r:"W", tip:"sc Heerenveen (D) 2-1"     },
      { r:"W", tip:"FC Utrecht (E) 0-1"        },
      { r:"W", tip:"Excelsior (D) 5-1"         },
      { r:"W", tip:"FC Groningen (D) 4-0"      },
      { r:"W", tip:"Fortuna Sittard (E) 0-3"   },
      { r:"W", tip:"Feyenoord (D) 4-1"         },
      { r:"W", tip:"N.E.C. (E) 2-3"            },
      { r:"W", tip:"Telstar (E) 0-5"           },
      { r:"W", tip:"Go Ahead Eagles (D) 3-0"   },
      { r:"W", tip:"FC Volendam (D) 2-1"       },
      { r:"W", tip:"Excelsior (E) 1-4"         },
      { r:"L", tip:"AZ (E) 2-0"                },
      { r:"W", tip:"Fortuna Sittard (D) 3-1"   },
      { r:"D", tip:"N.E.C. (D) 1-1"            },
      { r:"W", tip:"PEC Zwolle (E) 2-3"        },
      { r:"W", tip:"FC Groningen (E) 3-4"      },
      { r:"W", tip:"Sparta Rotterdam (D) 5-3"  },
      { r:"L", tip:"Feyenoord (E) 5-3"         },
      { r:"W", tip:"FC Twente (D) 2-0"         },
      { r:"D", tip:"Heracles Almelo (E) 2-2"   },
      { r:"W", tip:"NAC Breda (E) 2-4"         },
      { r:"W", tip:"PSV (D) 3-2"               },
      { r:"W", tip:"FC Utrecht (D) 4-1"        },
      { r:"W", tip:"sc Heerenveen (E) 1-6"     },
    ],

    standings: [
      { pos:1,  team:"Feyenoord",       j:34, g:29, n:3, l:2,  bp:95,  bc:28, db: 67, pts:90, zone:"promo" },
      { pos:2,  team:"Ajax",            j:34, g:27, n:3, l:4,  bp:108, bc:39, db: 69, pts:84, zone:"promo", highlight:true },
      { pos:3,  team:"PSV",             j:34, g:23, n:6, l:5,  bp:73,  bc:40, db: 33, pts:75, zone:"promo" },
      { pos:4,  team:"AZ",              j:34, g:18, n:10,l:6,  bp:75,  bc:47, db: 28, pts:64              },
      { pos:5,  team:"FC Groningen",    j:34, g:18, n:6, l:10, bp:71,  bc:53, db: 18, pts:60              },
      { pos:6,  team:"FC Utrecht",      j:34, g:14, n:5, l:15, bp:56,  bc:52, db:  4, pts:47              },
      { pos:7,  team:"N.E.C.",          j:34, g:12, n:9, l:13, bp:52,  bc:50, db:  2, pts:45              },
      { pos:8,  team:"PEC Zwolle",      j:34, g:12, n:9, l:13, bp:55,  bc:58, db: -3, pts:45              },
      { pos:9,  team:"Excelsior",       j:34, g:12, n:8, l:14, bp:46,  bc:58, db:-12, pts:44              },
      { pos:10, team:"Fortuna Sittard", j:34, g:11, n:9, l:14, bp:51,  bc:66, db:-15, pts:42              },
      { pos:11, team:"Go Ahead Eagles", j:34, g:11, n:6, l:17, bp:52,  bc:61, db: -9, pts:39              },
      { pos:12, team:"Sparta Rotterdam",j:34, g:9,  n:12,l:13, bp:51,  bc:61, db:-10, pts:39              },
      { pos:13, team:"FC Twente",       j:34, g:11, n:6, l:17, bp:48,  bc:63, db:-15, pts:39              },
      { pos:14, team:"Telstar",         j:34, g:9,  n:9, l:16, bp:51,  bc:69, db:-18, pts:36              },
      { pos:15, team:"FC Volendam",     j:34, g:10, n:4, l:20, bp:48,  bc:71, db:-23, pts:34              },
      { pos:16, team:"NAC Breda",       j:34, g:9,  n:3, l:22, bp:43,  bc:80, db:-37, pts:30, zone:"releg" },
      { pos:17, team:"sc Heerenveen",   j:34, g:6,  n:7, l:21, bp:27,  bc:63, db:-36, pts:25, zone:"releg" },
      { pos:18, team:"Heracles Almelo", j:34, g:5,  n:5, l:24, bp:42,  bc:85, db:-43, pts:20, zone:"releg" },
    ],
  },

  /* ─── SAISON 2026/27 ─────────────────────────────────── */
  {
    id:         "ajax-2026-27",
    year:       "2026/27",
    league:     "Eredivisie",
    position:   3,
    totalTeams: 18,
    points:     71,
    played:     34,
    wins:       22,
    draws:      5,
    losses:     7,
    gf:         73,
    ga:         32,
    promoted:   [],
    relegated:  ["FC Eindhoven", "Fortuna Sittard", "Roda JC"],

    scorers: [],
    assists: [],
    ratings: [],

    transfers: [
      { type: "buy",  name: "Vítězslav Jaroš",              from: "Liverpool",            date: "Juin 2026", amount: "12,25M €" },
      { type: "free", name: "Dan-Axel Zagadou",             from: "VfB Stuttgart",        date: "Juil. 2026"                  },
      { type: "free", name: "Julian Brandt",                from: "Borussia Dortmund",    date: "Juil. 2026"                  },
      { type: "free", name: "Jorge Franco",                 from: "Zaragoza B",           date: "Juil. 2026"                  },
      { type: "buy",  name: "Wojciech Szczęsny",            from: "Barcelone",            date: "Juil. 2026", amount: "7,5M €"  },
      { type: "buy",  name: "Arnau Puigmal",                from: "Almería",              date: "Juil. 2026", amount: "14,5M €" },
      { type: "buy",  name: "Pablo Solari",                 from: "Spartak Moscou",       date: "Sep. 2026", amount: "6,25M €" },
      { type: "buy",  name: "Nadiem Amiri",                 from: "FSV Mainz 05",         date: "Jan. 2027", amount: "15,75M €" },
      { type: "free", name: "Sailson Furtado Fernandes",    from: "FC Dordrecht",         date: "Jan. 2027"                  },
      { type: "loan", name: "Luis Sinisterra",              from: "Bournemouth",          date: "Jan. 2027"                  },
      { type: "loan", name: "Nicolò Cambiaghi",             from: "Bologna",              date: "Fév. 2027"                  },
    ],

    departures: [
      { type: "sell", name: "Steven Berghuis",       to: "León",                   date: "Juin 2026",  amount: "275K €"  },
      { type: "sell", name: "Kian Fitz-Jim",         to: "Norwich",                date: "Juin 2026",  amount: "5,25M €" },
      { type: "sell", name: "Chuba Akpom",           to: "Ipswich",                date: "Juin 2026",  amount: "8M €"    },
      { type: "free", name: "Oleksandr Zinchenko",   to: "Vigo",                   date: "Juil. 2026"                  },
      { type: "sell", name: "Joël Schingtienne",    to: "Standard",               date: "Juil. 2026", amount: "2,1M €"  },
      { type: "free", name: "Lucas Jetten",          to: "Benfica",                date: "Juil. 2026"                  },
      { type: "free", name: "Ethan Butera",          to: "Bournemouth",            date: "Juil. 2026"                  },
      { type: "sell", name: "Maarten Paes",          to: "Al-Riyadh",              date: "Juil. 2026", amount: "2M €"    },
      { type: "loan", name: "Jinairo Johnson",       to: "FC Eindhoven",           date: "Juil. 2026"                  },
      { type: "sell", name: "Ahmetcan Kaplan",       to: "Al-Taawun",              date: "Juil. 2026", amount: "1,5M €"  },
      { type: "loan", name: "Jorge Franco",          to: "Sant Andreu",            date: "Juil. 2026"                  },
      { type: "loan", name: "Pharell Nash",          to: "Wolves",                 date: "Juil. 2026"                  },
      { type: "loan", name: "Aaron Bouwman",         to: "Arminia Bielefeld",      date: "Juil. 2026"                  },
      { type: "loan", name: "Daniel Johan Skaarud",  to: "NAC Breda",              date: "Juil. 2026"                  },
      { type: "loan", name: "Hasan Ayyildiz",        to: "Bursaspor",              date: "Juil. 2026"                  },
      { type: "sell", name: "Owen Wijndal",          to: "Wolves",                 date: "Aoû. 2026",  amount: "5,25M €" },
      { type: "sell", name: "Sivert Mannsverk",      to: "Bergame",                date: "Aoû. 2026",  amount: "16M €"   },
      { type: "loan", name: "Marvyn Muzungu",        to: "Nancy",                  date: "Aoû. 2026"                  },
      { type: "loan", name: "Mark Engel",            to: "Vitesse",                date: "Sep. 2026"                  },
      { type: "sell", name: "Levi Acheampong",       to: "PSV",                    date: "Sep. 2026",  amount: "575K €"  },
      { type: "loan", name: "Emre Ünüvar",           to: "Heracles Almelo",        date: "Sep. 2026"                  },
      { type: "loan", name: "David Kalokoh",         to: "Estoril Praia",          date: "Sep. 2026"                  },
      { type: "loan", name: "Sean Steur",            to: "Fortuna Düsseldorf",     date: "Jan. 2027"                  },
      { type: "loan", name: "Martin Henrion",        to: "SK Lierse",              date: "Jan. 2027"                  },
      { type: "loan", name: "Luka Vieillevoye",      to: "Penafiel",               date: "Jan. 2027"                  },
      { type: "loan", name: "Nafairon Landvreugd",   to: "Vitesse",                date: "Jan. 2027"                  },
      { type: "loan", name: "Oliver Edvardsen",      to: "Norwich",                date: "Jan. 2027"                  },
      { type: "loan", name: "Andrea Compagno",       to: "Girona",                 date: "Jan. 2027"                  },
      { type: "loan", name: "Lucas Rosa",            to: "Espanyol",               date: "Jan. 2027"                  },
      { type: "loan", name: "Skye Vink",             to: "Heracles Almelo",        date: "Fév. 2027"                  },
      { type: "loan", name: "Mark Verkuijl",         to: "Heracles Almelo",        date: "Fév. 2027"                  },
      { type: "sell", name: "Takahiro Ohgihara",     to: "G-Osaka",                date: "Fév. 2027",  amount: "60K €"   },
      { type: "loan", name: "Josip Šutalo",          to: "Dinamo Zagreb",          date: "Fév. 2027"                  },
    ],

    cup: {
      name: "KNVB Beker",
      rounds: [
        { result: "W", round: "2e tour", score: "0 – 5", opponent: "IJsselmeervogels (E)" },
        { result: "W", round: "3e tour", score: "2 – 1", opponent: "FC Groningen (D)"     },
        { result: "W", round: "Quart",   score: "2 – 4", opponent: "NAC Breda (E)"        },
        { result: "W", round: "Demi",    score: "2 – 3", opponent: "FC Volendam (E)"      },
        { result: "L", round: "Finale",  score: "2 – 1", opponent: "Feyenoord (N)"        },
      ],
    },

    cup2: {
      name:  "UEFA Champions League",
      phase: "Phase de championnat : 22e sur 36 · 2V 3N 3D · 9 pts → Barrage · Éliminé par Lille (2-3 cumulé)",
      rounds: [
        { result: "D", round: "Barrage · Aller",  score: "1 – 1", opponent: "LOSC Lille (D)"            },
        { result: "L", round: "Barrage · Retour", score: "2 – 1", opponent: "LOSC Lille (E) — 2-3 élim." },
      ],
    },

    playoffs: null,

    splash: {
      eyebrow:  "2026/27 · Ajax Amsterdam · Saison 2",
      lines:    ["SUR LE PODIUM.", "CAP SUR LA C1."],
      sub:      "Eredivisie · 3e · 71 pts · Qualifié en Ligue des Champions",
      tagline:  "Derrière Feyenoord et le PSV, l'Ajax décroche son billet direct pour la Ligue des Champions — malgré une finale de coupe cruelle perdue contre l'éternel rival.",
    },

    matches: [
      { r:"W", tip:"PSV (E) 0-2"                },
      { r:"W", tip:"Roda JC (D) 4-3"            },
      { r:"W", tip:"PEC Zwolle (E) 1-2"         },
      { r:"W", tip:"AZ (D) 2-1"                 },
      { r:"W", tip:"ADO Den Haag (E) 0-2"       },
      { r:"L", tip:"Feyenoord (D) 2-3"          },
      { r:"D", tip:"FC Utrecht (D) 0-0"         },
      { r:"W", tip:"Telstar (E) 0-2"            },
      { r:"D", tip:"Fortuna Sittard (D) 2-2"    },
      { r:"W", tip:"Sparta Rotterdam (D) 4-1"   },
      { r:"W", tip:"FC Eindhoven (E) 1-4"       },
      { r:"W", tip:"Excelsior (D) 4-0"          },
      { r:"W", tip:"N.E.C. (E) 0-1"             },
      { r:"W", tip:"FC Groningen (D) 3-1"       },
      { r:"L", tip:"Go Ahead Eagles (E) 1-0"    },
      { r:"W", tip:"FC Volendam (E) 0-3"        },
      { r:"W", tip:"FC Twente (D) 6-3"          },
      { r:"W", tip:"Telstar (D) 4-1"            },
      { r:"D", tip:"Fortuna Sittard (E) 0-0"    },
      { r:"L", tip:"PSV (D) 1-2"                },
      { r:"L", tip:"FC Utrecht (E) 1-0"         },
      { r:"W", tip:"Excelsior (E) 1-2"          },
      { r:"D", tip:"N.E.C. (D) 0-0"             },
      { r:"D", tip:"FC Groningen (E) 1-1"       },
      { r:"W", tip:"ADO Den Haag (D) 4-0"       },
      { r:"L", tip:"Feyenoord (E) 1-0"          },
      { r:"W", tip:"FC Volendam (D) 4-0"        },
      { r:"L", tip:"AZ (E) 3-2"                 },
      { r:"L", tip:"Sparta Rotterdam (E) 2-1"   },
      { r:"W", tip:"FC Eindhoven (D) 4-0"       },
      { r:"W", tip:"Roda JC (E) 2-3"            },
      { r:"W", tip:"PEC Zwolle (D) 1-0"         },
      { r:"W", tip:"Go Ahead Eagles (D) 1-0"    },
      { r:"W", tip:"FC Twente (E) 1-2"          },
    ],

    standings: [
      { pos:1,  team:"Feyenoord",        j:34, g:28, n:5,  l:1,  bp:102, bc:21, db: 81, pts:89, zone:"promo" },
      { pos:2,  team:"PSV",              j:34, g:27, n:5,  l:2,  bp:84,  bc:29, db: 55, pts:86, zone:"promo" },
      { pos:3,  team:"Ajax",             j:34, g:22, n:5,  l:7,  bp:73,  bc:32, db: 41, pts:71, zone:"promo", highlight:true },
      { pos:4,  team:"FC Utrecht",       j:34, g:19, n:6,  l:9,  bp:59,  bc:44, db: 15, pts:63              },
      { pos:5,  team:"Go Ahead Eagles",  j:34, g:18, n:5,  l:11, bp:71,  bc:56, db: 15, pts:59              },
      { pos:6,  team:"N.E.C.",           j:34, g:17, n:7,  l:10, bp:50,  bc:39, db: 11, pts:58              },
      { pos:7,  team:"FC Twente",        j:34, g:15, n:9,  l:10, bp:52,  bc:57, db: -5, pts:54              },
      { pos:8,  team:"AZ",               j:34, g:16, n:5,  l:13, bp:67,  bc:42, db: 25, pts:53              },
      { pos:9,  team:"FC Groningen",     j:34, g:13, n:9,  l:12, bp:52,  bc:55, db: -3, pts:48              },
      { pos:10, team:"ADO Den Haag",     j:34, g:13, n:6,  l:15, bp:48,  bc:52, db: -4, pts:45              },
      { pos:11, team:"FC Volendam",      j:34, g:11, n:8,  l:15, bp:50,  bc:62, db:-12, pts:41              },
      { pos:12, team:"Excelsior",        j:34, g:8,  n:12, l:14, bp:40,  bc:52, db:-12, pts:36              },
      { pos:13, team:"Sparta Rotterdam", j:34, g:10, n:5,  l:19, bp:52,  bc:74, db:-22, pts:35              },
      { pos:14, team:"Telstar",          j:34, g:9,  n:2,  l:23, bp:40,  bc:85, db:-45, pts:29              },
      { pos:15, team:"PEC Zwolle",       j:34, g:5,  n:10, l:19, bp:35,  bc:61, db:-26, pts:25              },
      { pos:16, team:"FC Eindhoven",     j:34, g:5,  n:8,  l:21, bp:35,  bc:67, db:-32, pts:23, zone:"releg" },
      { pos:17, team:"Fortuna Sittard",  j:34, g:3,  n:11, l:20, bp:38,  bc:76, db:-38, pts:20, zone:"releg" },
      { pos:18, team:"Roda JC",          j:34, g:4,  n:8,  l:22, bp:31,  bc:75, db:-44, pts:20, zone:"releg" },
    ],
  },

]
